import json
doc = open("zhenjiu_doc.md", encoding="utf-8", errors="ignore").read()

# 29 curated entries (grounded in 人纪·针灸 / TCM). attribute labels per meridian.
E = [
    # ---- 督脉 (8) ----
    {"name": "中枢", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，第10胸椎棘突下凹陷中。主治黄疸、呕吐、腹满、腰脊强痛。",
     "location": "背部，后正中线上，第10胸椎棘突下凹陷中。",
     "clinicalNotes": "倪师：中枢在第十椎下，治黄疸、脾胃病、腰背强痛，沿棘突下直刺。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "陶道", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，第1胸椎棘突下凹陷中，足太阳与督脉之会。主治项强、发热、疟疾、癫痫。",
     "location": "背部，后正中线上，第1胸椎棘突下凹陷中。",
     "clinicalNotes": "倪师：陶道在第一椎下（大椎下第一椎），俯而取之，足太阳与督脉之会。治疟、感冒发热、项强，针或灸皆宜。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "脑户", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，后正中线，枕外隆凸上缘凹陷中。主治头重、头晕、项强、癫狂、瘿瘤。",
     "location": "头部，后发际正中直上2.5寸，枕外隆凸上缘凹陷中。",
     "clinicalNotes": "倪师：脑户在枕骨下、风府上，不可深刺（下为延髓），治头风、项强、眩晕。",
     "needling": "", "moxibustion": "", "contraindication": "深刺易伤延髓，禁深刺"},
    {"name": "强间", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，后发际正中直上4寸。主治头痛、目眩、项强、癫狂。",
     "location": "头部，后发际正中直上4寸（脑户上1.5寸）。",
     "clinicalNotes": "倪师：强间在脑户上一寸半，治头痛、项强、癫痫，沿皮刺。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "顖会", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴（即囟会），前发际正中直上2寸。主治头痛、眩晕、鼻塞、惊痫、嗜睡。",
     "location": "头部，前发际正中直上2寸（百会前3寸）。",
     "clinicalNotes": "倪师：顖会在上星后一寸陷中，《铜人》灸二七壮至七壮。小儿囟门未合者禁针，可灸。治头痛、鼻塞、神昏。",
     "needling": "小儿囟门未合禁针", "moxibustion": "", "contraindication": "小儿囟门未闭合者禁针"},
    {"name": "神庭", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，前发际正中直上0.5寸。主治头痛、眩晕、失眠、惊悸、癫狂。",
     "location": "头部，前发际正中直上0.5寸。",
     "clinicalNotes": "倪师：神庭在发际上五分，治神志病、头痛、眼疾，禁深刺。",
     "needling": "", "moxibustion": "", "contraindication": "禁深刺"},
    {"name": "兑端", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，上唇尖端红唇与皮肤移行处。主治昏迷、晕厥、中暑、癫狂、口噤、唇动。",
     "location": "面部，上唇尖端，红唇与皮肤移行处。",
     "clinicalNotes": "倪师：兑端在嘴唇上方尖端，治昏倒、中暑、癫痫急性发作，常与水沟（人中）配伍急救。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "龈交", "meridian": "督脉", "attribute": "经穴（督脉）",
     "description": "督脉穴，上唇系带与齿龈连接处。主治昏迷、癫痫、口噤、齿龈肿痛、鼻渊。",
     "location": "上唇系带与齿龈连接处。",
     "clinicalNotes": "倪师：龈交在嘴唇里面、上唇系带与牙龈交界处，任督二脉在此交会（龈交唇内任督毕）。治癫痫、急救常用，三棱针点刺出血。",
     "needling": "点刺出血，一般不留针", "moxibustion": "", "contraindication": ""},
    # ---- 任脉 (7) ----
    {"name": "曲骨", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，耻骨联合上缘中点。主治小便不利、遗尿、遗精、阳痿、痛经、带下。",
     "location": "下腹部，前正中线上，耻骨联合上缘中点。",
     "clinicalNotes": "倪师：曲骨在耻骨上方，近胞中，治小便、妇科、男科病。针时排空膀胱，向下斜刺，不可深（下有膀胱）。",
     "needling": "", "moxibustion": "", "contraindication": "孕妇慎用；深刺伤膀胱"},
    {"name": "建里", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，脐上3寸。主治胃痛、呕吐、食欲不振、腹胀。",
     "location": "上腹部，前正中线上，脐上3寸。",
     "clinicalNotes": "倪师：建里在中脘下、下脘上，治胃脘痛、消化不良，胃病下针常用。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "中庭", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，胸骨体下缘（膻中下1.6寸）。主治胸胁胀满、心痛、呕吐、小儿吐乳。",
     "location": "胸部，前正中线上，胸骨体下缘，平第5肋间。",
     "clinicalNotes": "倪师：中庭在膻中下一寸六，玉堂下一寸，治胸满、心胸痛、呕逆。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "玉堂", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，平第3肋间（膻中上1.6寸）。主治咳嗽、气喘、胸痛、咽喉肿痛。",
     "location": "胸部，前正中线上，胸骨体上，平第3肋间。",
     "clinicalNotes": "倪师：玉堂在紫宫下一寸六，华盖下一寸六，治咳逆、气喘、胸痛。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "紫宫", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，平第2肋间。主治咳嗽、气喘、胸闷、胸痛。",
     "location": "胸部，前正中线上，胸骨体上，平第2肋间。",
     "clinicalNotes": "倪师：紫宫在华盖下一寸六，玉堂上一寸六，治咳逆、胸满、喘促。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "华盖", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，平第1肋间（璇玑下1寸）。主治咳嗽、气喘、胸胁胀痛。",
     "location": "胸部，前正中线上，胸骨角中点，平第1肋间。",
     "clinicalNotes": "倪师：华盖在璇玑下一寸，紫宫上一寸六，治咳逆、喘促、胸胁痛。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "璇玑", "meridian": "任脉", "attribute": "经穴（任脉）",
     "description": "任脉穴，前正中线上，胸骨柄中央，天突下1寸。主治咳嗽、气喘、胸痛、咽喉肿痛。",
     "location": "胸部，前正中线上，胸骨柄中央，天突下1寸。",
     "clinicalNotes": "倪师：璇玑在天突下一寸，华盖上一寸，治咳逆、胸满、喉痹。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    # ---- 肝经 (4) ----
    {"name": "中封", "meridian": "足厥阴肝经", "attribute": "经穴（肝经经穴）",
     "description": "肝经经穴（金），内踝前1寸，胫骨前肌腱内侧凹陷处。主治疝气、遗精、小便不利、腹胀、下肢痿痹。",
     "location": "足背，内踝前1寸，胫骨前肌腱内侧凹陷处（商丘与解溪之间）。",
     "clinicalNotes": "倪师：中封是肝经的经穴（属金），在商丘与解溪中间、内踝前。肝经实证（如疝气、小便不利）泻中封，实则泻其子。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "阴廉", "meridian": "足厥阴肝经", "attribute": "经穴（肝经）",
     "description": "肝经穴，气冲穴下2寸，耻骨结节下方。主治月经不调、带下、少腹痛、腿股痛。",
     "location": "大腿内侧，气冲穴（曲骨旁）下2寸，耻骨结节下方。",
     "clinicalNotes": "倪师：阴廉在气冲穴旁开五分下两寸处。肝经走少腹，治妇科、少腹疼、腿股痛。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "急脉", "meridian": "足厥阴肝经", "attribute": "经穴（肝经）",
     "description": "肝经穴，耻骨结节外侧，股动脉搏动处。主治少腹痛、疝气、阴挺、阴茎痛。",
     "location": "耻骨结节外侧，气冲外下1寸，股动脉搏动处。",
     "clinicalNotes": "倪师：急脉在阴部旁、动脉处，治疝气、阴部痛。下针避开动脉，免出血。",
     "needling": "避开股动脉", "moxibustion": "", "contraindication": "避开动脉，禁直刺过深"},
    {"name": "期门", "meridian": "足厥阴肝经", "attribute": "肝之募穴（足厥阴、足太阴、阴维之会）",
     "description": "肝之募穴，第6肋间隙，前正中线旁开4寸。主治胸胁胀痛、呕吐、呃逆、腹胀、奔豚、肝积。",
     "location": "胸部，乳头直下，第6肋间隙，前正中线旁开4寸。",
     "clinicalNotes": "倪师：期门是肝的募穴（脏病取募），肝痛、肝病下针期门。肝家病变（肝积、肝硬化、肝癌）常取期门配上脘、下脘。针沿肋间隙向外斜刺0.5-0.8寸，不可深刺（下为肝）。",
     "needling": "沿肋间隙斜刺0.5-0.8寸", "moxibustion": "", "contraindication": "不可深刺，肝肿大时忌直刺"},
    # ---- 胆经 (4) ----
    {"name": "中渎", "meridian": "足少阳胆经", "attribute": "经穴（胆经）",
     "description": "胆经穴，大腿外侧，腘横纹上7寸（风市下2寸）。主治下肢痿痹、麻木、坐骨神经痛。",
     "location": "大腿外侧正中，腘横纹上7寸，风市下2寸。",
     "clinicalNotes": "倪师：中渎在风市下二寸，治腿外侧麻、坐骨神经痛、中风半身不遂之下肢痿痹。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "足临泣", "meridian": "足少阳胆经", "attribute": "经穴（胆经俞穴，通带脉）",
     "description": "胆经俞穴，八脉交会穴通带脉。足背第4、5跖骨底结合部前方凹陷。主治头痛、目赤、胁痛、疟疾、月经不调、带下、瘰疬。",
     "location": "足背，第4、5跖骨底结合部前方凹陷中。",
     "clinicalNotes": "倪师：足临泣是胆经俞穴，又通带脉，治带下、月经不调、少阳经病、疟疾。与丘墟、侠溪配伍治胆经实证；带脉病（如白带）必用。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "侠溪", "meridian": "足少阳胆经", "attribute": "经穴（胆经荥穴）",
     "description": "胆经荥穴（水），足背第4、5趾间趾蹼缘后方赤白肉际。主治头痛、眩晕、耳鸣、耳聋、胁肋痛、乳痈、热病。",
     "location": "足背，第4、5趾间，趾蹼缘后方赤白肉际处。",
     "clinicalNotes": "倪师：侠溪是胆经荣穴（属水），主身热，胆经实证、少阳头痛、耳鸣、目眩下侠溪，实则泻其子。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "足窍阴", "meridian": "足少阳胆经", "attribute": "经穴（胆经井穴）",
     "description": "胆经井穴（金），第4趾外侧趾甲角旁0.1寸。主治头痛、目赤、耳聋、咽喉肿痛、热病、失眠。",
     "location": "足第4趾外侧趾甲角旁约0.1寸。",
     "clinicalNotes": "倪师：足窍阴是胆经井穴，井主心下满，治胆经热、头痛、喉痹、失眠，点刺出血。",
     "needling": "点刺出血", "moxibustion": "", "contraindication": ""},
    # ---- 奇穴 (6) ----
    {"name": "百虫窝", "meridian": "经外奇穴", "attribute": "奇穴",
     "description": "经外奇穴，髌底内侧端上3寸（血海穴上1寸）。主治皮肤瘙痒、湿疹、荨麻疹、虫积、蛔虫病。",
     "location": "大腿内侧，髌底内侧端上3寸，血海上1寸处。",
     "clinicalNotes": "倪师：百虫窝在血海上一寸，治皮肤痒、湿疹、虫积。针血海、百虫窝、委中出血，痒证特效。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "四缝", "meridian": "经外奇穴", "attribute": "奇穴（儿科）",
     "description": "经外奇穴，第2-5指掌面近侧指间关节中央。主治小儿疳积、百日咳、消化不良。",
     "location": "手指，第2-5指掌面，近侧指间关节中央，每指1穴。",
     "clinicalNotes": "倪师：四缝在食指到小指中间关节缝，挑破挤出黄水治小儿疳积、消化不良，是儿科常用奇穴。",
     "needling": "点刺挤黄水", "moxibustion": "", "contraindication": ""},
    {"name": "夜尿点", "meridian": "经外奇穴", "attribute": "奇穴",
     "description": "经外奇穴，足底足跟正中赤白肉际处（或掌面小指远端指关节横纹中点）。主治小儿夜尿、遗尿。",
     "location": "足底，足跟正中赤白肉际处。",
     "clinicalNotes": "倪师：夜尿点在脚后跟或手掌小指下方，专治夜尿、遗尿，灸或针皆效。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "子宫", "meridian": "经外奇穴", "attribute": "奇穴（妇人）",
     "description": "经外奇穴（子宫穴），脐下4寸（中极）旁开3寸。主治月经不调、痛经、崩漏、不孕、子宫脱垂。",
     "location": "下腹部，脐下4寸（中极）旁开3寸。",
     "clinicalNotes": "倪师：子宫穴在中极旁开三寸，妇人病、痛经、不孕、子宫下垂皆可用，常配关元、三阴交。",
     "needling": "", "moxibustion": "", "contraindication": "孕妇慎用"},
    {"name": "安眠", "meridian": "经外奇穴", "attribute": "奇穴",
     "description": "经外奇穴（安眠穴），翳风与风池连线中点。主治失眠、眩晕、头痛、心悸。",
     "location": "颈部，翳风穴与风池穴连线中点。",
     "clinicalNotes": "倪师：安眠穴在风池与翳风中间，专治失眠，针之得气即效，常配神门、三阴交。",
     "needling": "", "moxibustion": "", "contraindication": ""},
    {"name": "颈夹脊", "meridian": "经外奇穴", "attribute": "奇穴（夹脊）",
     "description": "经外奇穴（夹脊穴），各椎棘突下旁开0.5寸，从颈1至腰5每侧17穴。主治相应节段脊椎及内脏病。",
     "location": "背部，第1颈椎至第5腰椎各椎棘突下旁开0.5寸，左右各17穴。",
     "clinicalNotes": "倪师：夹脊穴在督脉旁开五分，从颈椎到腰椎每一椎旁都有，按节段治对应脏腑与脊痛，是华佗夹脊用法。",
     "needling": "", "moxibustion": "", "contraindication": ""},
]

# sanity: doc membership
not_in_doc = [e["name"] for e in E if e["name"] not in doc and e["name"].rstrip("穴") not in doc]
print("entries to add        :", len(E))
print("NOT found in doc     :", not_in_doc)

d = json.load(open("assets/data/acupoints.json", encoding="utf-8"))
existing_norm = {a["name"].rstrip("穴") for a in d["acupoints"]}
dups = [e["name"] for e in E if e["name"].rstrip("穴") in existing_norm]
print("DUPLICATE names       :", dups)

d["acupoints"].extend(E)
d["total"] = len(d["acupoints"])
json.dump(d, open("assets/data/acupoints.json", "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("new total             :", d["total"])
