// 问诊公式 · 终审版（v3.2）驱动的规则数据层
// 本文件是「七步问诊」的唯一方剂判定依据：每首方 = 必选信号(required,★) + 参考信号(reference,Q)
// 选项号与《问诊公式_终审版 v3.2》一一对应（1-based）。扩展症状(ext*)为文档中"其他不适"类信号。
// v3.2 相对 v3.1 修正：甘姜苓术汤 Q7 改小便清长、大黄附子汤 Q1 兼容身热、麻黄汤补气喘参考、
// 防己黄芪汤改身重浮肿、大陷胸丸补项强、旋覆代赭归噫气行、新增炙甘草汤、失眠链补结代。

// ============ 12 问 key ============
const String kQ1 = 'temperature'; // 寒热 7（不可跳）
const String kQ2 = 'pulse';       // 脉象 15（可跳，⑬不清楚）
const String kQ3 = 'thirst';      // 渴饮 7（不可跳）
const String kQ4 = 'sweating';    // 汗出 7
const String kQ5 = 'pain';        // 疼痛/不适 20
const String kQ6 = 'stool';       // 大便 8
const String kQ7 = 'urine';       // 小便 7
const String kQ8 = 'appetite';    // 胃口 8
const String kQ9 = 'sleep';       // 睡眠 6
const String kQ10 = 'energy';     // 精神 6
const String kQ11 = 'menstrual';  // 月经/性功能 8（可跳）
const String kQ12 = 'vomit_type'; // 呕吐类型 7（Q8=⑧触发）

// ============ 12 问 canonical 选项（顺序=文档编号） ============
const Map<String, List<String>> qOptions = {
  kQ1: [
    '手脚温热', '手心脚心热', '往来寒热', '头热脚冷', '上半身热下半身冷',
    '手脚冰冷', '全身怕冷',
  ],
  kQ2: [
    '浮', '沉', '迟', '数', '滑', '涩', '弦', '紧', '细', '微', '弱', '缓',
    '不清楚', '结', '代',
  ],
  kQ3: ['不渴', '渴想喝冷水', '渴想喝热水', '渴但不想喝', '口苦口干', '消渴', '大渴'],
  kQ4: ['不容易出汗', '稍微活动就出汗', '睡觉出汗', '白天也出汗', '但头汗出', '手足汗出', '大汗出'],
  kQ5: [
    '不痛', '头痛前额', '头痛两侧', '头痛后脑', '胸胁胀痛', '腹痛喜按', '腹痛拒按',
    '关节游走痛', '身体痛骨节痛', '心下痞满按之软', '身痒皮肤痒', '心下痞硬', '腹胀满',
    '身体麻木不仁', '咽中异物感', '胸痛心痛彻背', '巅顶痛', '心悸怔忡', '头晕目眩', '腰痛腰冷',
  ],
  kQ6: ['正常成形', '便秘', '稀拉肚子', '先硬后稀', '水样便', '便脓血', '下利清谷', '大便色黑'],
  kQ7: ['正常淡黄色', '次数多量少', '次数少颜色深', '夜尿多', '小便不利', '小便黄赤', '小便清长'],
  kQ8: ['正常三餐', '没有胃口', '特别能吃', '饿但不想吃', '想吃冷的', '想吃热的', '食不下', '恶心呕吐'],
  kQ9: ['一觉到天亮', '半夜1-3点醒', '半夜3-5点醒', '整夜睡不着', '多梦易醒', '嗜睡睡不够'],
  kQ10: ['精力充沛', '容易疲倦', '但欲寐', '烦躁不安', '说话没力气', '气上撞心'],
  kQ11: ['没有此症状', '月经正常', '痛经量少色暗有块', '月经量多色红', '月经不调先后无定期', '已绝经', '性功能正常', '性功能减退腰酸'],
  kQ12: ['恶心但不呕', '干呕含吐涎沫', '呕吐少量', '呕吐剧烈', '食入即吐', '朝食暮吐暮食朝吐', '噫气嗳气'],
};

// ============ 扩展症状（文档"其他不适"类信号；供 Q12 后多选捕获） ============
const Map<String, String> extSymptoms = {
  'neck_stiff': '项背僵硬/项背强几几',
  'nape_stiff': '项强如柔痉',
  'chest_oppression': '胸闷/气短',
  'epigastric_reverse_full': '心下逆满',
  'epigastric_full_pain': '心下满微痛',
  'epigastric_palpitation': '心下悸',
  'umbilical_palpitation': '脐下悸',
  'epigastric_hard_full': '心下硬满（无热）',
  'epigastric_to_abdomen_hard': '心下至少腹硬满剧痛',
  'chest_diaphragm_hard': '胸膈心下硬满（项强）',
  'epigastric_press_pain': '心下按之痛（局限）',
  'chest_hard_full': '胸中痞硬（气上冲咽）',
  'epigastric_solid_full': '心下坚满（利反快）',
  'epigastric_hard_solid': '心下痞坚（面色黧黑）',
  'epigastric_pi': '心下痞（心中痞）',
  'lesser_abdomen_acute': '少腹急结',
  'lesser_abdomen_hard': '少腹硬满',
  'lesser_abdomen_full': '少腹满',
  'lesser_abdomen_pain': '少腹满痛/刺痛',
  'lesser_abdomen_mass': '少腹癥块',
  'lesser_abdomen_inner_urgent': '少腹里急',
  'jaundice': '身黄（如橘子色）',
  'jaundice_dark_forehead': '身黄额上黑',
  'jaundice_dry_skin': '身黄皮肤枯燥',
  'jaundice_abdominal_full': '身黄腹满',
  'cough_wheeze': '咳喘/喉中水鸡声',
  'wheeze_no_lie': '喘/咳不得卧',
  'chest_full_no_lie': '胸满不能卧',
  'chest_qi_block': '胸中气塞',
  'chest_bi_dyspnea': '胸痹喘息咳唾短气',
  'chest_no_lie': '胸痛不得卧',
  'hypochondriac_qi_rise': '胁下气逆',
  'heart_pi': '心中痞/胁下逆抢心',
  'chest_bi_fluctuate': '胸痹缓急（时缓时急）',
  'heart_pain_back': '心痛彻背背痛彻心',
  'abdomen_cold_thunder': '腹中寒气雷鸣切痛',
  'chest_heart_great_cold': '心胸中大寒痛',
  'hypochondriac_partial_pain': '胁下偏痛',
  'periumbilical_pain': '绕脐痛',
  'abdomen_pain': '腹中痛（里急）',
  'abdomen_colic': '腹痛阵作时止',
  'abdomen_dull_pain': '腹中㽲痛',
  'abdomen_full': '腹满',
  'heart_abdomen_acute': '心腹胀满卒痛',
  'liver_attachment': '胸胁痛（常欲蹈其胸）',
  'vexing_heat': '心中懊憹/胸中窒闷',
  'vexing_heat_pain': '心中懊憹热痛',
  'short_breath': '短气',
  'body_twitch': '身瞤动',
  'back_aversion_cold': '背恶寒',
  'cold_hands_feet': '手足寒',
  'day_vex_night_calm': '昼日烦躁夜安静',
  'face_red': '面赤（假热）',
  'body_no_aversion_face_red': '身反不恶寒面赤',
  'vexed_fright': '烦惊',
  'delirium': '谵语/如狂',
  'mania': '发狂/善忘',
  'sad_want_cry': '喜悲伤欲哭',
  'frequent_yawn': '数欠伸',
  'pregnancy': '妊娠',
  'postpartum': '产后',
  'throat_pus_blood': '咽喉不利唾脓血',
  'watery_diarrhea': '泄利不止',
  'hematemesis': '吐血',
  'hematochezia_after': '便血先便后血',
  'hematochezia_before': '便血先血后便',
  'skin_rough': '肌肤甲错',
  'leukorrhea': '带下异常',
  'vulva_cold': '阴中寒',
  'vulva_ulcer': '阴中蚀疮',
  'uterine_bleeding': '漏下不止',
  'postpartum_bleeding': '半产后下血不止',
  'chong_ren_deficiency': '冲任虚损',
  'amenorrhea': '经水闭不利',
  'uterine_hard': '脏坚癖不止',
  'uterus_mass_history': '宿有癥病',
  'lip_dry': '唇口干燥',
  'menopause_diarrhea': '年五十所下利数十日',
  'joint_noon_worse': '关节痛日晡所剧',
  'all_joints_pain': '诸肢节疼痛',
  'body_emaciated': '身体尫羸',
  'joint_cant_bend': '关节痛不可屈伸',
  'body_pain_cant_turn': '身体疼烦不能转侧',
  'tugging_pain': '掣痛不得屈伸',
  'blood_qi_stab': '血气刺痛',
  'retained_fluid': '留饮（心下坚满利反快）',
  'suspended_fluid': '悬饮（胸胁引痛）',
  'phlegm_fluid': '支饮（膈间喘满痞坚）',
  'phlegm_fluid_dizzy': '心下有支饮冒眩',
  'yellow_sweat': '黄汗（脉浮汗出）',
  'alarm_palpitation': '惊悸',
  'heart_fire': '心火亢盛迫血',
  'spleen_not_control': '脾不统血',
  'qi_rush_throat': '气上冲咽不得息',
  'cold_hernia': '寒疝绕脐痛',
  'cold_hernia_abdomen': '寒疝腹痛胁痛里急',
  'limb_numb': '手足不仁',
  'edema': '身重浮肿',
};

// ============ 公式规则 ============
class FormulaRule {
  final String name;
  final String meridian; // 太阳/少阳/阳明/太阴/少阴/厥阴/金匮
  final Map<String, List<int>> required;  // qKey -> 必选选项号(★)，任一满足
  final Map<String, List<int>> reference; // qKey -> 参考选项号(Q)，用于打分
  final Set<String> extRequired;          // 必选扩展症状(★)
  final Set<String> extReference;        // 参考扩展症状(Q)
  final String differential;              // 鉴别说明

  const FormulaRule({
    required this.name,
    required this.meridian,
    this.required = const {},
    this.reference = const {},
    this.extRequired = const {},
    this.extReference = const {},
    this.differential = '',
  });
}

const List<FormulaRule> allFormulaRules = [
  // ===================== 太阳 =====================
  // A. 中风表虚
  FormulaRule(
    name: '桂枝汤',
    meridian: '太阳',
    required: {kQ1: [1], kQ4: [2, 4], kQ2: [12]},
    reference: {kQ3: [1], kQ5: [1, 4], kQ10: [2]},
    differential: '有汗＋脉缓＝桂枝汤标志组合；与麻黄汤区别在有汗。',
  ),
  FormulaRule(
    name: '桂枝加葛根汤',
    meridian: '太阳',
    required: {kQ1: [1], kQ4: [2, 4], kQ5: [4]},
    extRequired: {'neck_stiff'},
    reference: {kQ2: [12], kQ3: [1], kQ10: [2]},
    differential: '桂枝汤证＋项背强几几 → 加葛根。',
  ),
  FormulaRule(
    name: '桂枝加附子汤',
    meridian: '太阳',
    required: {kQ4: [4], kQ2: [10], kQ1: [6, 7]},
    reference: {kQ3: [1], kQ7: [5], kQ10: [2]},
    differential: '汗漏不止＋恶寒脉微 → 阳虚漏汗，加附子回阳固表。',
  ),
  FormulaRule(
    name: '桂枝去芍药汤',
    meridian: '太阳',
    required: {kQ1: [1]},
    extRequired: {'chest_oppression'},
    reference: {kQ2: [4], kQ10: [2]},
    differential: '太阳病误下后胸满 → 去芍药之阴柔。',
  ),
  FormulaRule(
    name: '桂枝去芍药加附子汤',
    meridian: '太阳',
    required: {kQ1: [6, 7]},
    extRequired: {'chest_oppression'},
    reference: {kQ2: [10], kQ10: [2]},
    differential: '去芍药汤证＋恶寒脉微 → 再加附子。',
  ),
  FormulaRule(
    name: '桂枝新加汤',
    meridian: '太阳',
    required: {kQ5: [9], kQ2: [2, 3]},
    reference: {kQ1: [1], kQ3: [1], kQ10: [2]},
    differential: '发汗后身痛不减反重＋脉沉迟 → 气营两虚。',
  ),
  FormulaRule(
    name: '桂枝麻黄各半汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1], kQ5: [11]},
    reference: {kQ2: [1], kQ10: [2]},
    differential: '发热恶寒如疟＋身痒＋无汗 → 表郁轻证。',
  ),
  FormulaRule(
    name: '桂枝二麻黄一汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1, 2]},
    reference: {kQ2: [1, 12], kQ5: [11], kQ10: [2]},
    differential: '比各半汤更轻，寒热一日再发。',
  ),
  FormulaRule(
    name: '桂枝二越婢一汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1], kQ3: [2]},
    reference: {kQ2: [1, 12], kQ5: [1], kQ10: [2]},
    differential: '表郁轻证＋微有内热 → 小发汗兼清里。',
  ),
  // B. 伤寒表实
  FormulaRule(
    name: '麻黄汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1], kQ2: [1, 8]},
    reference: {kQ3: [1], kQ5: [2, 3, 4, 9], kQ10: [2]},
    extReference: {'cough_wheeze'},
    differential: '无汗＋恶寒＋脉浮紧，三者缺一不可；兼气喘者加杏仁（麻黄汤本治喘家）。',
  ),
  FormulaRule(
    name: '葛根汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1], kQ5: [4]},
    extRequired: {'neck_stiff'},
    reference: {kQ2: [1, 8], kQ3: [1], kQ10: [2]},
    differential: '麻黄汤证＋项背强 → 加葛根；与桂枝加葛根汤区别在无汗。',
  ),
  FormulaRule(
    name: '大青龙汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1], kQ10: [4]},
    reference: {kQ2: [1, 8], kQ5: [9], kQ3: [1, 2]},
    differential: '麻黄汤证＋烦躁 → 内有郁热，石膏清之。脉微弱汗出恶风者禁用。',
  ),
  FormulaRule(
    name: '小青龙汤',
    meridian: '太阳',
    required: {kQ1: [7], kQ4: [1], kQ3: [1, 3]},
    reference: {kQ5: [5], kQ7: [5], kQ6: [3], kQ10: [2]},
    differential: '外寒内饮 → 不渴或喜热饮＋清稀痰＋咳喘。若渴者去半夏加栝蒌根。',
  ),
  // C. 兼证变证
  FormulaRule(
    name: '麻杏石甘汤',
    meridian: '太阳',
    required: {kQ1: [1], kQ4: [2, 5], kQ3: [2]},
    extRequired: {'cough_wheeze'},
    reference: {kQ2: [4, 5]},
    differential: '汗出而喘＋身热＋渴 → 热壅于肺。',
  ),
  FormulaRule(
    name: '葛根芩连汤',
    meridian: '太阳',
    required: {kQ1: [1], kQ6: [3, 5], kQ4: [2]},
    reference: {kQ2: [4, 5], kQ3: [2]},
    differential: '身热下利＋脉数 → 热迫大肠。',
  ),
  FormulaRule(
    name: '桂枝甘草汤',
    meridian: '太阳',
    required: {kQ5: [18], kQ10: [2]},
    differential: '发汗过多后心悸欲按 → 心阳虚。',
  ),
  FormulaRule(
    name: '桂枝加桂汤',
    meridian: '太阳',
    required: {kQ10: [6], kQ5: [18]},
    differential: '气从少腹上冲 → 奔豚。',
  ),
  FormulaRule(
    name: '苓桂术甘汤',
    meridian: '太阳',
    required: {kQ5: [19]},
    extRequired: {'epigastric_reverse_full'},
    reference: {kQ7: [5], kQ10: [2]},
    differential: '心下逆满＋起则头眩 → 水饮上犯。',
  ),
  FormulaRule(
    name: '苓桂枣甘汤',
    meridian: '太阳',
    required: {kQ10: [6]},
    extRequired: {'umbilical_palpitation'},
    differential: '脐下悸动 → 欲作奔豚，水停下焦。',
  ),
  FormulaRule(
    name: '茯苓甘草汤',
    meridian: '太阳',
    required: {kQ3: [1]},
    extRequired: {'epigastric_palpitation'},
    reference: {kQ7: [5], kQ8: [2]},
    differential: '心下悸＋不渴 → 水停中焦，与五苓散鉴别。',
  ),
  FormulaRule(
    name: '桂枝去桂加茯苓白术汤',
    meridian: '太阳',
    required: {kQ7: [5]},
    extRequired: {'epigastric_full_pain'},
    reference: {kQ4: [1], kQ1: [1], kQ5: [4]},
    differential: '头项强痛＋心下满＋小便不利 → 水气内停。',
  ),
  FormulaRule(
    name: '厚朴生姜半夏甘草人参汤',
    meridian: '太阳',
    required: {kQ5: [13], kQ10: [2]},
    reference: {kQ8: [2]},
    differential: '发汗后腹胀满 → 脾虚气滞，虚中夹实。',
  ),
  FormulaRule(
    name: '小建中汤',
    meridian: '太阳',
    required: {kQ5: [6, 18], kQ2: [9, 11]},
    reference: {kQ10: [2], kQ9: [5]},
    differential: '腹中急痛喜按＋心悸＋脉细 → 中焦虚寒。',
  ),
  FormulaRule(
    name: '黄芪建中汤',
    meridian: '太阳',
    required: {kQ5: [6], kQ1: [6, 7], kQ4: [2, 4]},
    reference: {kQ2: [9, 11], kQ10: [2]},
    differential: '小建中汤证＋自汗恶寒更甚 → 气虚偏重。',
  ),
  FormulaRule(
    name: '内补当归建中汤',
    meridian: '太阳',
    required: {kQ5: [6], kQ11: [3]},
    reference: {kQ1: [7], kQ10: [2, 5]},
    differential: '小建中汤证＋月经量少色暗 → 产后血虚。',
  ),
  FormulaRule(
    name: '栀子豉汤',
    meridian: '太阳',
    required: {kQ9: [4], kQ10: [4]},
    extReference: {'vexing_heat'},
    reference: {kQ1: [1]},
    differential: '虚烦不得眠＋反复颠倒＋心中懊憹 → 热扰胸膈。',
  ),
  FormulaRule(
    name: '栀子生姜豉汤',
    meridian: '太阳',
    required: {kQ9: [4], kQ10: [4], kQ12: [3]},
    differential: '栀子豉汤证＋呕 → 加生姜和胃止呕。',
  ),
  FormulaRule(
    name: '栀子干姜汤',
    meridian: '太阳',
    required: {kQ1: [1], kQ6: [3]},
    extReference: {'chest_oppression'},
    reference: {kQ10: [2]},
    differential: '身热＋大便溏 → 上热下寒。',
  ),
  FormulaRule(
    name: '栀子厚朴汤',
    meridian: '太阳',
    required: {kQ10: [4], kQ5: [13]},
    reference: {kQ1: [1]},
    differential: '心烦＋腹满 → 热壅气滞。',
  ),
  FormulaRule(
    name: '栀子柏皮汤',
    meridian: '太阳',
    required: {kQ1: [1]},
    extRequired: {'jaundice'},
    reference: {kQ7: [6]},
    differential: '身黄＋发热 → 湿热发黄偏于热。',
  ),
  FormulaRule(
    name: '麻黄连翘赤小豆汤',
    meridian: '太阳',
    required: {kQ4: [1]},
    extRequired: {'jaundice'},
    reference: {kQ1: [1], kQ7: [6], kQ6: [3]},
    differential: '身黄＋无汗＋表证 → 湿热发黄偏于表。',
  ),
  // 真武汤（太阳篇变证）：见★三项已并入少阴篇真武汤，不重复列方。
  FormulaRule(
    name: '茯苓四逆汤',
    meridian: '太阳',
    required: {kQ1: [6, 7], kQ10: [4], kQ2: [10]},
    reference: {kQ3: [3, 1], kQ9: [4], kQ10: [2]},
    differential: '恶寒脉微＋烦躁 → 阴阳两虚。',
  ),
  FormulaRule(
    name: '干姜附子汤',
    meridian: '太阳',
    required: {kQ1: [6, 7]},
    extRequired: {'day_vex_night_calm'},
    reference: {kQ2: [10], kQ10: [4]},
    differential: '昼烦夜静＋脉微 → 阳气暴虚。',
  ),
  // v3.2 新增：炙甘草汤（复脉汤）——脉结代心动悸，阴阳两虚
  FormulaRule(
    name: '炙甘草汤',
    meridian: '太阳',
    required: {kQ2: [14, 15], kQ5: [18]},
    reference: {kQ10: [2], kQ1: [1, 2], kQ3: [2], kQ9: [4]},
    differential: '脉结代＋心动悸 → 阴阳两虚，通阳复脉。与加减法（小建中→炙甘草）衔接。',
  ),
  // D. 蓄水蓄血
  FormulaRule(
    name: '五苓散',
    meridian: '太阳',
    required: {kQ3: [2], kQ7: [5]},
    reference: {kQ2: [1], kQ1: [1], kQ6: [3]},
    differential: '口渴＋水入则吐＋小便不利 → 膀胱气化不行。',
  ),
  FormulaRule(
    name: '猪苓汤',
    meridian: '太阳',
    required: {kQ3: [2], kQ7: [5, 6]},
    reference: {kQ9: [4], kQ2: [9], kQ1: [2]},
    differential: '渴而不呕＋小便不利＋心烦不寐 → 阴虚水热互结。',
  ),
  FormulaRule(
    name: '桃核承气汤',
    meridian: '太阳',
    required: {kQ11: [3]},
    extRequired: {'lesser_abdomen_acute'},
    reference: {kQ10: [4], kQ6: [2]},
    differential: '少腹急结＋如狂＋经血色暗 → 蓄血轻证。',
  ),
  FormulaRule(
    name: '抵当汤',
    meridian: '太阳',
    required: {kQ6: [8]},
    extRequired: {'lesser_abdomen_hard'},
    reference: {kQ2: [6], kQ11: [3], kQ10: [4]},
    differential: '少腹硬满＋发狂/善忘＋大便黑 → 蓄血重证。',
  ),
  FormulaRule(
    name: '抵当丸',
    meridian: '太阳',
    required: {kQ2: [6]},
    extRequired: {'lesser_abdomen_full'},
    reference: {kQ11: [3], kQ10: [2]},
    differential: '少腹满但不如抵当汤急重 → 蓄血缓证。',
  ),
  // E. 结胸与痞证
  FormulaRule(
    name: '大陷胸汤',
    meridian: '太阳',
    required: {kQ6: [2]},
    extRequired: {'epigastric_to_abdomen_hard'},
    reference: {kQ2: [2, 8], kQ3: [2], kQ1: [1]},
    differential: '从心下至少腹硬满而痛不可近 → 大结胸。',
  ),
  FormulaRule(
    name: '大陷胸丸',
    meridian: '太阳',
    required: {},
    extRequired: {'chest_diaphragm_hard', 'nape_stiff'},
    reference: {kQ1: [1], kQ6: [2]},
    differential: '结胸偏于上 → 项强如柔痉。',
  ),
  FormulaRule(
    name: '小陷胸汤',
    meridian: '太阳',
    required: {kQ2: [5]},
    extRequired: {'epigastric_press_pain'},
    reference: {kQ1: [1]},
    differential: '心下按之痛（非硬满）＋脉浮滑 → 小结胸。',
  ),
  FormulaRule(
    name: '三物小白散',
    meridian: '太阳',
    required: {kQ1: [7]},
    extRequired: {'epigastric_hard_full'},
    reference: {kQ2: [2, 3], kQ3: [1], kQ6: [2]},
    differential: '心下硬满＋不发热不渴 → 寒实结胸。',
  ),
  FormulaRule(
    name: '半夏泻心汤',
    meridian: '太阳',
    required: {kQ5: [10], kQ6: [3], kQ12: [3]},
    reference: {kQ2: [12], kQ10: [2]},
    differential: '心下痞满按之不痛＋肠鸣下利 → 寒热错杂痞。',
  ),
  FormulaRule(
    name: '大黄黄连泻心汤',
    meridian: '太阳',
    required: {kQ5: [10], kQ2: [1]},
    reference: {kQ3: [2], kQ10: [4]},
    differential: '心下痞＋按之濡＋脉关上浮 → 纯热痞。',
  ),
  FormulaRule(
    name: '附子泻心汤',
    meridian: '太阳',
    required: {kQ5: [10], kQ1: [7], kQ4: [2, 4]},
    differential: '心下痞＋恶寒汗出 → 热痞兼表阳虚。',
  ),
  FormulaRule(
    name: '生姜泻心汤',
    meridian: '太阳',
    required: {kQ5: [12], kQ12: [7]},
    reference: {kQ6: [3], kQ10: [2]},
    differential: '痞硬＋干噫食臭＋雷鸣下利 → 水热互结。',
  ),
  FormulaRule(
    name: '甘草泻心汤',
    meridian: '太阳',
    required: {kQ5: [12], kQ6: [3], kQ12: [2]},
    reference: {kQ8: [8, 2], kQ10: [4]},
    differential: '痞硬＋下利极重＋干呕心烦 → 胃虚痞利俱甚。',
  ),
  FormulaRule(
    name: '旋覆代赭汤',
    meridian: '太阳',
    required: {kQ5: [12], kQ12: [7]},
    differential: '痞硬＋噫气不除＋不以下利为主 → 胃虚痰阻气逆。',
  ),

  // ===================== 少阳 =====================
  FormulaRule(
    name: '小柴胡汤',
    meridian: '少阳',
    required: {kQ1: [3], kQ5: [5], kQ3: [5]},
    reference: {kQ9: [2, 3], kQ8: [2], kQ10: [4], kQ7: [2], kQ12: [3]},
    differential: '往来寒热＋胸胁苦满＋口苦目眩 → 少阳提纲。',
  ),
  FormulaRule(
    name: '大柴胡汤',
    meridian: '少阳',
    required: {kQ5: [5, 7], kQ3: [5]},
    reference: {kQ6: [2, 3], kQ10: [4], kQ2: [7], kQ12: [3, 4]},
    differential: '少阳证＋心下急痛＋便秘 → 少阳阳明合病。',
  ),
  FormulaRule(
    name: '柴胡桂枝汤',
    meridian: '少阳',
    required: {kQ1: [3], kQ5: [5, 8, 9]},
    reference: {kQ1: [7], kQ4: [2], kQ10: [2]},
    differential: '发热微恶寒＋支节烦痛＋微呕 → 太阳少阳并病。',
  ),
  FormulaRule(
    name: '柴胡加芒硝汤',
    meridian: '少阳',
    required: {kQ1: [3], kQ6: [2]},
    reference: {kQ5: [5], kQ3: [5], kQ1: [1]},
    differential: '小柴胡证＋潮热不大便 → 少阳兼阳明燥实（正气偏虚）。',
  ),
  FormulaRule(
    name: '柴胡加龙骨牡蛎汤',
    meridian: '少阳',
    required: {kQ5: [5], kQ10: [4]},
    extReference: {'vexed_fright'},
    reference: {kQ9: [4], kQ7: [5], kQ1: [1]},
    differential: '胸满烦惊＋小便不利＋谵语 → 少阳枢机不利＋水饮。',
  ),
  FormulaRule(
    name: '柴胡桂枝干姜汤',
    meridian: '少阳',
    required: {kQ1: [3], kQ3: [1]},
    reference: {kQ5: [5], kQ10: [2], kQ7: [5]},
    extReference: {'nape_stiff'},
    differential: '往来寒热＋心烦＋不渴＋头汗 → 少阳兼水饮内结。',
  ),

  // ===================== 阳明 =====================
  FormulaRule(
    name: '白虎汤',
    meridian: '阳明',
    required: {kQ1: [1], kQ3: [7], kQ4: [7]},
    reference: {kQ2: [4, 5], kQ10: [4], kQ5: [1]},
    differential: '大热＋大渴＋大汗＋脉洪大 → 四大症俱。',
  ),
  FormulaRule(
    name: '白虎加人参汤',
    meridian: '阳明',
    required: {kQ1: [1], kQ3: [7], kQ10: [2]},
    reference: {kQ4: [7], kQ2: [4, 5], kQ10: [5]},
    differential: '白虎汤证＋大烦渴不解＋背微恶寒 → 津气两伤。',
  ),
  FormulaRule(
    name: '调胃承气汤',
    meridian: '阳明',
    required: {kQ6: [2], kQ1: [1], kQ10: [4]},
    reference: {kQ3: [2], kQ2: [4], kQ5: [7]},
    differential: '便秘＋蒸蒸发热＋谵语 → 燥实为主，无大满大痛。',
  ),
  FormulaRule(
    name: '小承气汤',
    meridian: '阳明',
    required: {kQ6: [2], kQ5: [7]},
    reference: {kQ1: [1], kQ10: [4], kQ2: [4, 5]},
    differential: '便秘＋腹大满不通 → 满为主，热次之。',
  ),
  FormulaRule(
    name: '大承气汤',
    meridian: '阳明',
    required: {kQ6: [2], kQ1: [1]},
    extRequired: {'periumbilical_pain'},
    reference: {kQ10: [4], kQ2: [2, 4], kQ5: [13], kQ3: [2]},
    differential: '痞满燥实坚俱备 → 绕脐痛＋潮热谵语＋手足濈然汗出。',
  ),
  FormulaRule(
    name: '麻子仁丸',
    meridian: '阳明',
    required: {kQ6: [2], kQ5: [6]},
    reference: {kQ1: [1, 7], kQ2: [6]},
    differential: '大便干结＋小便数 → 脾约（津液不足非实热）。',
  ),
  // v3.2 全量补全：蜜煎导/猪胆汁导（导法外治，便秘硬便近肛门不出）
  // 收口：仅"便秘"太宽（倪海厦经方：蜜煎导只用于汗出多→津液内竭的导法特例，非便秘常法），
  // 故必选加 kQ4 汗出类，使无汗纯便秘不再静默归此方、转为待问诊。
  FormulaRule(
    name: '蜜煎导猪胆汁导',
    meridian: '阳明',
    required: {kQ6: [2], kQ4: [2, 4, 7]},
    differential: '汗出多＋便秘＋硬便欲解不得（津液内竭）→ 导法外治（蜜煎导/猪胆汁导），不可攻下。',
  ),
  FormulaRule(
    name: '茵陈蒿汤',
    meridian: '阳明',
    required: {kQ7: [6]},
    extRequired: {'jaundice'},
    reference: {kQ1: [1], kQ3: [2], kQ5: [13], kQ6: [2]},
    differential: '身黄鲜明＋腹满＋小便不利 → 湿热并重。',
  ),
  FormulaRule(
    name: '栀子大黄汤',
    meridian: '阳明',
    required: {kQ8: [5]},
    extRequired: {'jaundice', 'vexing_heat_pain'},
    reference: {kQ1: [1], kQ10: [4], kQ7: [6]},
    differential: '身黄＋心中懊憹或热痛 → 热重于湿，偏于心下。',
  ),
  FormulaRule(
    name: '硝石矾石散',
    meridian: '阳明',
    required: {kQ1: [1]},
    extRequired: {'jaundice_dark_forehead'},
    reference: {kQ7: [6], kQ11: [3, 4]},
    differential: '黄疸久久不退＋额上黑 → 女劳疸（肾虚夹瘀）。',
  ),
  FormulaRule(
    name: '猪膏发煎',
    meridian: '阳明',
    extReference: {'jaundice_dry_skin'},
    differential: '黄疸久久＋肌肤枯燥 → 燥结发黄。',
  ),
  FormulaRule(
    name: '大黄硝石汤',
    meridian: '阳明',
    required: {kQ7: [6]},
    extRequired: {'jaundice_abdominal_full'},
    reference: {kQ1: [1], kQ6: [2], kQ3: [2]},
    differential: '黄疸腹满小便赤 → 湿热壅盛，里实重症。',
  ),

  // ===================== 太阴 =====================
  FormulaRule(
    name: '理中丸',
    meridian: '太阴',
    required: {kQ1: [6, 7], kQ6: [3, 7], kQ8: [2, 7]},
    reference: {kQ2: [10, 3], kQ3: [3, 1], kQ5: [6], kQ10: [2, 5]},
    differential: '腹满而吐＋食不下＋自利不渴 → 太阴虚寒提纲。',
  ),
  FormulaRule(
    name: '桂枝加芍药汤',
    meridian: '太阴',
    required: {kQ5: [6], kQ1: [1]},
    reference: {kQ2: [12], kQ10: [2]},
    differential: '太阳误下后腹满时痛（非太阴本证）→ 气滞不和。',
  ),
  FormulaRule(
    name: '桂枝加大黄汤',
    meridian: '太阴',
    required: {kQ5: [7], kQ6: [2]},
    reference: {kQ1: [1]},
    differential: '桂枝加衣汤证＋大实痛 → 兼有实邪。',
  ),

  // ===================== 少阴 =====================
  FormulaRule(
    name: '四逆汤',
    meridian: '少阴',
    required: {kQ1: [6], kQ2: [10], kQ10: [3]},
    reference: {kQ3: [1, 3], kQ6: [7], kQ7: [7], kQ5: [9], kQ8: [7]},
    differential: '四肢厥逆＋脉微欲绝＋但欲寐 → 回阳救逆第一方。',
  ),
  FormulaRule(
    name: '通脉四逆汤',
    meridian: '少阴',
    required: {kQ2: [10], kQ6: [7]},
    extRequired: {'body_no_aversion_face_red'},
    reference: {kQ1: [6], kQ10: [3]},
    differential: '下利清谷不止＋脉微欲绝＋身反不恶寒 → 阴盛格阳重证。',
  ),
  FormulaRule(
    name: '白通汤',
    meridian: '少阴',
    required: {kQ2: [10], kQ6: [7, 3], kQ1: [6]},
    extReference: {'face_red'},
    reference: {kQ10: [3], kQ5: [9]},
    differential: '下利＋脉微＋厥逆 → 阴盛戴阳（面赤）。',
  ),
  FormulaRule(
    name: '白通加猪胆汁汤',
    meridian: '少阴',
    required: {kQ2: [10], kQ6: [7], kQ10: [4]},
    reference: {kQ1: [6]},
    differential: '白通汤证＋利不止厥逆无脉＋干呕烦 → 阴阳格拒。',
  ),
  FormulaRule(
    name: '附子汤',
    meridian: '少阴',
    required: {kQ1: [6, 7], kQ5: [9]},
    extReference: {'back_aversion_cold', 'cold_hands_feet'},
    reference: {kQ2: [10, 2], kQ10: [3]},
    differential: '身体骨节疼痛＋手足寒＋脉沉 → 少阴寒湿身痛。',
  ),
  FormulaRule(
    name: '真武汤',
    meridian: '少阴',
    required: {kQ1: [6, 7], kQ7: [5, 2], kQ5: [19]},
    reference: {kQ2: [10], kQ5: [6], kQ4: [2], kQ6: [3], kQ10: [2, 3]},
    extReference: {'body_twitch'},
    differential: '少阴阳虚水泛。太阳变证以身瞤动为主，少阴本证以腹痛下利为辨；临证见必选三项即主方，兼症随证加减。',
  ),
  FormulaRule(
    name: '麻黄附子细辛汤',
    meridian: '少阴',
    required: {kQ1: [7], kQ2: [10, 2], kQ4: [1]},
    reference: {kQ10: [3]},
    differential: '发热＋脉沉＋但欲寐 → 少阴兼表（太少两感）。',
  ),
  FormulaRule(
    name: '麻黄附子甘草汤',
    meridian: '少阴',
    required: {kQ1: [7], kQ2: [10], kQ4: [1], kQ10: [3]},
    differential: '比麻附辛更缓 → 少阴兼表微证。',
  ),
  FormulaRule(
    name: '桃花汤',
    meridian: '少阴',
    required: {kQ6: [6], kQ5: [6]},
    reference: {kQ1: [6], kQ10: [2], kQ2: [9]},
    differential: '下利便脓血色暗不鲜＋腹痛喜按 → 虚寒滑脱。与白头翁汤区别：此寒证。',
  ),
  FormulaRule(
    name: '黄连阿胶汤',
    meridian: '少阴',
    required: {kQ9: [4], kQ1: [2], kQ2: [9, 4]},
    reference: {kQ10: [4], kQ3: [2]},
    differential: '心中烦不得卧＋手足心热＋脉细数 → 阴虚火旺。与四逆汤区别：此为阴虚。',
  ),
  FormulaRule(
    name: '猪苓汤',
    meridian: '少阴',
    required: {kQ3: [2], kQ7: [5]},
    reference: {kQ9: [4], kQ2: [9], kQ1: [2]},
    differential: '渴＋小便不利＋心烦不寐 → 阴虚水热互结。',
  ),
  FormulaRule(
    name: '四逆散',
    meridian: '少阴',
    required: {kQ1: [6], kQ5: [5, 6]},
    reference: {kQ2: [7], kQ10: [4], kQ6: [3, 5], kQ12: [2]},
    differential: '四逆（手足不温非厥逆）＋胸胁脘腹痛＋脉弦 → 阳郁气滞。与四逆汤区别：此为气郁非阳虚，脉弦非脉微。',
  ),

  // ===================== 厥阴 =====================
  FormulaRule(
    name: '乌梅丸',
    meridian: '厥阴',
    required: {kQ1: [4]},
    extRequired: {'abdomen_colic'},
    reference: {kQ8: [4], kQ3: [5], kQ6: [3, 7], kQ1: [6, 7]},
    differential: '腹痛阵发＋呕吐蛔虫/上热下寒 → 蛔厥/久利。',
  ),
  FormulaRule(
    name: '干姜黄芩黄连人参汤',
    meridian: '厥阴',
    required: {kQ1: [4], kQ12: [5]},
    reference: {kQ6: [3], kQ3: [5], kQ10: [4]},
    differential: '食入口即吐＋下利 → 上热下寒，寒格。',
  ),
  FormulaRule(
    name: '麻黄升麻汤',
    meridian: '厥阴',
    required: {kQ1: [4]},
    extReference: {'throat_pus_blood', 'watery_diarrhea'},
    reference: {kQ6: [3], kQ7: [5], kQ1: [1, 7]},
    differential: '咽喉不利唾脓血＋泄利不止＋手足厥逆 → 上热下寒最甚。',
  ),
  FormulaRule(
    name: '当归四逆汤',
    meridian: '厥阴',
    required: {kQ1: [6], kQ2: [9]},
    reference: {kQ5: [8], kQ11: [3]},
    differential: '手足厥寒＋脉细欲绝 → 血虚寒凝，不同于四逆汤的阳衰。',
  ),
  FormulaRule(
    name: '当归四逆加吴茱萸生姜汤',
    meridian: '厥阴',
    required: {kQ1: [6], kQ2: [9], kQ12: [2]},
    reference: {kQ5: [6], kQ11: [3]},
    differential: '当归四逆汤证＋内有久寒（呕涎沫/腹痛）。',
  ),
  FormulaRule(
    name: '吴茱萸汤',
    meridian: '厥阴',
    required: {kQ1: [6, 7], kQ12: [2]},
    reference: {kQ5: [17], kQ10: [2]},
    differential: '三联征：干呕吐涎沫＋巅顶痛＋手足厥冷。',
  ),
  FormulaRule(
    name: '白头翁汤',
    meridian: '厥阴',
    required: {kQ6: [6], kQ5: [7]},
    reference: {kQ2: [4], kQ3: [2], kQ1: [1]},
    differential: '下利脓血色鲜＋里急后重＋腹痛 → 热毒痢疾。',
  ),
  // v3.2 全量补全：白头翁加甘草阿胶汤（白头翁汤证＋产后气血虚）
  FormulaRule(
    name: '白头翁加甘草阿胶汤',
    meridian: '厥阴',
    required: {kQ6: [6], kQ5: [7]},
    reference: {kQ2: [9], kQ10: [2]},
    differential: '白头翁汤证＋产后气血虚 → 加甘草阿胶扶正。',
  ),
  FormulaRule(
    name: '瓜蒂散',
    meridian: '厥阴',
    extRequired: {'chest_hard_full'},
    extReference: {'qi_rush_throat'},
    reference: {kQ8: [8]},
    differential: '胸中痞硬＋气上冲咽喉 → 痰食壅塞，因势利导。',
  ),

  // ===================== 金匮 =====================
  // A. 痉湿暍
  FormulaRule(
    name: '栝蒌桂枝汤',
    meridian: '金匮',
    required: {kQ1: [1], kQ5: [4]},
    extRequired: {'neck_stiff'},
    reference: {kQ2: [2, 3], kQ4: [2, 4]},
    differential: '有汗＋身体强几几 → 柔痉（痉病津亏）。',
  ),
  FormulaRule(
    name: '麻黄加术汤',
    meridian: '金匮',
    required: {kQ1: [7], kQ4: [1], kQ5: [8]},
    reference: {kQ2: [1, 8]},
    differential: '麻黄汤证＋湿家身烦痛 → 发汗兼祛湿。',
  ),
  FormulaRule(
    name: '麻杏薏甘汤',
    meridian: '金匮',
    required: {kQ5: [8], kQ1: [1]},
    extReference: {'joint_noon_worse'},
    reference: {kQ4: [2], kQ2: [1]},
    differential: '一身尽疼＋发热日晡加剧 → 风湿化热。',
  ),
  FormulaRule(
    name: '防己黄芪汤',
    meridian: '金匮',
    required: {kQ4: [2, 4]},
    extRequired: {'edema'},
    reference: {kQ1: [7], kQ7: [5], kQ2: [11], kQ5: [8]},
    differential: '汗出恶风＋身重浮肿 → 表虚风湿。',
  ),
  FormulaRule(
    name: '桂枝附子汤',
    meridian: '金匮',
    required: {kQ1: [7], kQ5: [8]},
    reference: {kQ4: [1], kQ2: [1, 6, 11]},
    differential: '身体疼烦不能转侧＋不呕不渴 → 风湿在表。',
  ),
  FormulaRule(
    name: '白术附子汤',
    meridian: '金匮',
    required: {kQ1: [7], kQ5: [8], kQ6: [3]},
    reference: {kQ4: [1], kQ2: [1, 6, 11]},
    differential: '桂枝附子汤证＋大便稀小便自利 → 去桂加术。',
  ),
  FormulaRule(
    name: '甘草附子汤',
    meridian: '金匮',
    required: {kQ5: [8], kQ1: [7], kQ4: [2]},
    extReference: {'tugging_pain'},
    reference: {kQ7: [5]},
    differential: '骨节疼烦掣痛不得屈伸＋汗出短气 → 风湿俱盛。',
  ),
  // B. 百合狐惑
  FormulaRule(
    name: '百合地黄汤',
    meridian: '金匮',
    required: {kQ9: [4], kQ10: [4], kQ3: [2, 3]},
    reference: {kQ3: [5], kQ7: [6]},
    differential: '意欲食复不能食＋欲行复不能行＋如寒无寒如热无热 → 百合病。',
  ),
  // C. 中风历节
  FormulaRule(
    name: '桂枝芍药知母汤',
    meridian: '金匮',
    required: {kQ5: [8], kQ1: [7]},
    extReference: {'all_joints_pain', 'body_emaciated'},
    reference: {kQ4: [2], kQ10: [2]},
    differential: '诸肢节疼痛＋身体尫羸＋头眩短气 → 风湿历节（偏风湿热）。',
  ),
  FormulaRule(
    name: '乌头汤',
    meridian: '金匮',
    required: {kQ5: [8], kQ1: [7]},
    extReference: {'joint_cant_bend'},
    reference: {kQ4: [1], kQ5: [9]},
    differential: '关节剧痛不可屈伸＋不汗出 → 寒湿历节。',
  ),
  // D. 血痹虚劳
  FormulaRule(
    name: '黄芪桂枝五物汤',
    meridian: '金匮',
    required: {kQ5: [14], kQ1: [6]},
    extReference: {'limb_numb'},
    reference: {kQ4: [2], kQ2: [6]},
    differential: '肌肤麻木不仁＋脉微涩 → 血痹。与当归四逆区别：以麻木非冷痛。',
  ),
  FormulaRule(
    name: '桂枝加龙骨牡蛎汤',
    meridian: '金匮',
    required: {kQ4: [3, 4], kQ5: [18]},
    reference: {kQ9: [5], kQ11: [8], kQ10: [2], kQ1: [6], kQ2: [9, 10]},
    differential: '失精家＋少腹弦急＋目眩发落 → 虚劳失精。',
  ),
  FormulaRule(
    name: '八味肾气丸',
    meridian: '金匮',
    required: {kQ1: [6], kQ5: [20], kQ7: [4]},
    reference: {kQ10: [2], kQ11: [8], kQ2: [10, 2]},
    differential: '腰痛脚软＋下半身冷＋夜尿 → 肾阳不足。',
  ),
  FormulaRule(
    name: '酸枣仁汤',
    meridian: '金匮',
    required: {kQ9: [4], kQ1: [2]},
    reference: {kQ10: [2, 4], kQ2: [9]},
    differential: '虚劳虚烦不得眠 → 肝血虚。与黄连阿胶区别：酸枣仁偏血虚。',
  ),
  FormulaRule(
    name: '大黄䗪虫丸',
    meridian: '金匮',
    required: {kQ5: [6], kQ11: [3, 4]},
    extReference: {'skin_rough'},
    reference: {kQ10: [2], kQ2: [6]},
    differential: '五劳虚极羸瘦＋腹满不能食＋肌肤甲错 → 干血劳。',
  ),
  FormulaRule(
    name: '薯蓣丸',
    meridian: '金匮',
    required: {kQ10: [2], kQ1: [7]},
    reference: {kQ5: [9], kQ4: [2]},
    differential: '虚劳诸不足＋风气百疾 → 扶正祛邪。',
  ),
  // E. 肺痿肺痈
  FormulaRule(
    name: '射干麻黄汤',
    meridian: '金匮',
    required: {kQ1: [7]},
    extRequired: {'cough_wheeze'},
    reference: {kQ4: [1], kQ10: [2]},
    differential: '咳而上气＋喉中水鸡声 → 寒饮郁肺。',
  ),
  FormulaRule(
    name: '皂荚丸',
    meridian: '金匮',
    extReference: {'wheeze_no_lie'},
    differential: '咳逆上气＋时时吐浊但坐不得眠 → 痰浊壅肺。',
  ),
  FormulaRule(
    name: '麦门冬汤',
    meridian: '金匮',
    required: {kQ1: [2]},
    extRequired: {'cough_wheeze'},
    reference: {kQ3: [2], kQ10: [2]},
    differential: '火逆上气＋咽喉不利 → 虚火上炎。与甘草干姜汤区别：此为虚热。',
  ),
  FormulaRule(
    name: '葶苈大枣泻肺汤',
    meridian: '金匮',
    extRequired: {'chest_full_no_lie'},
    reference: {kQ1: [1], kQ4: [1]},
    differential: '肺痈喘不得卧＋胸满胀 → 实邪壅肺。',
  ),
  FormulaRule(
    name: '越婢加半夏汤',
    meridian: '金匮',
    required: {kQ1: [1]},
    extRequired: {'cough_wheeze'},
    reference: {kQ4: [2], kQ2: [1]},
    differential: '咳而上气＋其人喘＋目如脱状 → 饮热郁肺。',
  ),
  // F. 胸痹心痛
  FormulaRule(
    name: '栝蒌薤白白酒汤',
    meridian: '金匮',
    required: {kQ5: [16], kQ2: [7]},
    reference: {kQ10: [2]},
    differential: '胸痹喘息咳唾短气 → 胸阳不振痰阻。',
  ),
  FormulaRule(
    name: '栝蒌薤白半夏汤',
    meridian: '金匮',
    required: {kQ5: [16]},
    reference: {kQ2: [7], kQ10: [2]},
    differential: '比栝蒌薤白白酒汤更重 → 痰浊更甚。',
  ),
  FormulaRule(
    name: '枳实薤白桂枝汤',
    meridian: '金匮',
    required: {kQ5: [16]},
    extRequired: {'hypochondriac_qi_rise'},
    reference: {kQ2: [7]},
    differential: '心中痞＋留气结在胸 → 气滞偏重。',
  ),
  FormulaRule(
    name: '人参汤',
    meridian: '金匮',
    required: {kQ5: [16], kQ1: [6]},
    reference: {kQ5: [10], kQ10: [2]},
    differential: '胸痹＋心中痞＋胁下逆抢心 → 偏虚寒（即理中丸方）。',
  ),
  FormulaRule(
    name: '茯苓杏仁甘草汤',
    meridian: '金匮',
    required: {kQ5: [16], kQ7: [5]},
    differential: '胸痹短气＋水饮在肺。',
  ),
  FormulaRule(
    name: '橘枳姜汤',
    meridian: '金匮',
    extReference: {'chest_qi_block'},
    differential: '与茯苓杏仁甘草汤区别：橘枳姜无胸痛，偏痞满气滞在胃。',
  ),
  FormulaRule(
    name: '薏苡附子散',
    meridian: '金匮',
    required: {kQ5: [16]},
    reference: {kQ1: [6]},
    differential: '胸痹缓急（时缓时急）→ 寒湿。',
  ),
  FormulaRule(
    name: '乌头赤石脂丸',
    meridian: '金匮',
    required: {kQ5: [16]},
    reference: {kQ1: [6, 7], kQ2: [10]},
    differential: '心痛彻背背痛彻心不止 → 阴寒痼结。',
  ),
  // G. 腹满寒疝
  FormulaRule(
    name: '厚朴七物汤',
    meridian: '金匮',
    required: {kQ5: [7], kQ6: [2], kQ1: [1]},
    reference: {kQ2: [1, 4]},
    differential: '腹满＋发热＋便秘 → 表里俱病。',
  ),
  FormulaRule(
    name: '附子粳米汤',
    meridian: '金匮',
    required: {kQ12: [3]},
    extRequired: {'abdomen_cold_thunder'},
    reference: {kQ1: [6, 7], kQ8: [8]},
    differential: '腹中寒气雷鸣切痛＋胸胁逆满 → 脾胃虚寒。',
  ),
  FormulaRule(
    name: '厚朴三物汤',
    meridian: '金匮',
    required: {kQ5: [7], kQ6: [2]},
    reference: {kQ2: [4]},
    differential: '痛而闭 → 以痛为主（区别于小承气以满为主）。',
  ),
  FormulaRule(
    name: '大建中汤',
    meridian: '金匮',
    required: {kQ12: [5]},
    extRequired: {'chest_heart_great_cold'},
    reference: {kQ1: [6, 7]},
    extReference: {'abdomen_full'},
    differential: '心胸中大寒痛＋上下痛不可触近＋呕 → 大寒大虚。',
  ),
  FormulaRule(
    name: '大黄附子汤',
    meridian: '金匮',
    required: {kQ1: [1, 7]},
    extRequired: {'hypochondriac_partial_pain'},
    reference: {kQ2: [7], kQ6: [2]},
    differential: '胁下偏痛发热＋脉紧弦 → 寒积。',
  ),
  FormulaRule(
    name: '赤丸',
    meridian: '金匮',
    required: {kQ1: [6]},
    extRequired: {'abdomen_pain'},
    reference: {kQ8: [8]},
    differential: '寒气厥逆腹痛 → 寒饮。',
  ),
  FormulaRule(
    name: '大乌头煎',
    meridian: '金匮',
    required: {kQ1: [7]},
    extRequired: {'periumbilical_pain'},
    differential: '寒疝绕脐痛＋手足厥冷＋脉沉紧 → 沉寒痼冷。',
  ),
  FormulaRule(
    name: '当归生姜羊肉汤',
    meridian: '金匮',
    required: {kQ5: [6], kQ1: [7]},
    reference: {kQ11: [3], kQ10: [2]},
    differential: '寒疝腹痛＋胁痛里急 → 血虚有寒。',
  ),
  FormulaRule(
    name: '乌头桂枝汤',
    meridian: '金匮',
    required: {kQ1: [7]},
    extRequired: {'abdomen_pain'},
    reference: {kQ4: [1]},
    extReference: {'limb_numb'},
    differential: '寒疝腹痛＋手足不仁＋身疼痛 → 内外皆寒。',
  ),
  // H. 五脏风寒
  FormulaRule(
    name: '旋覆花汤',
    meridian: '金匮',
    extReference: {'liver_attachment'},
    reference: {kQ10: [2]},
    differential: '肝着 → 常欲蹈其胸上。',
  ),
  FormulaRule(
    name: '甘姜苓术汤',
    meridian: '金匮',
    required: {kQ5: [20], kQ1: [7], kQ7: [7]},
    reference: {kQ10: [2], kQ3: [1]},
    differential: '腰以下冷痛＋腰重如带五千钱＋小便清长 → 寒湿着于腰部（肾着汤）。',
  ),
  // I. 痰饮咳嗽
  FormulaRule(
    name: '甘遂半夏汤',
    meridian: '金匮',
    required: {kQ6: [2]},
    extRequired: {'epigastric_solid_full'},
    differential: '心下坚满＋利反快 → 留饮（攻逐）。',
  ),
  FormulaRule(
    name: '十枣汤',
    meridian: '金匮',
    required: {kQ7: [5]},
    extRequired: {'suspended_fluid'},
    reference: {kQ4: [2], kQ2: [5]},
    differential: '悬饮＋咳唾引痛＋心下痞硬 → 攻逐水饮。',
  ),
  FormulaRule(
    name: '木防己汤',
    meridian: '金匮',
    required: {kQ1: [1]},
    extRequired: {'epigastric_hard_solid'},
    reference: {kQ7: [5], kQ2: [4]},
    differential: '膈间支饮＋喘满心下痞坚＋面色黧黑 → 攻补兼施。',
  ),
  FormulaRule(
    name: '泽泻汤',
    meridian: '金匮',
    required: {kQ5: [19]},
    differential: '心下有支饮＋其人苦冒眩 → 水饮上冒。比苓桂术甘更重。',
  ),
  FormulaRule(
    name: '小半夏汤',
    meridian: '金匮',
    required: {kQ12: [2], kQ3: [1]},
    differential: '呕家＋不渴 → 痰饮呕吐基本方。',
  ),
  FormulaRule(
    name: '小半夏加茯苓汤',
    meridian: '金匮',
    required: {kQ12: [2], kQ5: [19]},
    reference: {kQ7: [5]},
    differential: '小半夏汤证＋眩悸 → 水饮更甚。',
  ),
  FormulaRule(
    name: '己椒苈黄丸',
    meridian: '金匮',
    required: {kQ6: [2]},
    extRequired: {'abdomen_full'},
    reference: {kQ3: [2], kQ7: [5]},
    differential: '腹满＋口舌干燥＋水走肠间沥沥有声 → 痰饮水走肠间。',
  ),
  // J. 消渴小便不利
  FormulaRule(
    name: '文蛤散',
    meridian: '金匮',
    required: {kQ3: [2], kQ7: [5]},
    differential: '渴欲饮水不止 → 渴。',
  ),
  FormulaRule(
    name: '栝蒌瞿麦丸',
    meridian: '金匮',
    required: {kQ1: [6], kQ3: [2], kQ7: [5]},
    reference: {kQ2: [10], kQ10: [2]},
    differential: '小便不利＋有水气＋其人若渴 → 下寒上燥。',
  ),
  FormulaRule(
    name: '蒲灰散滑石白鱼散茯苓戎盐汤',
    meridian: '金匮',
    required: {kQ7: [5]},
    extRequired: {'lesser_abdomen_full'},
    differential: '小便不利的三种轻证。',
  ),
  // K. 黄疸
  FormulaRule(
    name: '桂枝加黄芪汤',
    meridian: '金匮',
    required: {kQ4: [2]},
    extRequired: {'jaundice'},
    reference: {kQ1: [7], kQ7: [6]},
    differential: '黄疸脉浮＋汗出 → 表虚黄汗。',
  ),
  // L. 惊悸吐衄
  FormulaRule(
    name: '柏叶汤',
    meridian: '金匮',
    extReference: {'hematemesis'},
    differential: '吐血不止 → 中气虚寒吐血。',
  ),
  FormulaRule(
    name: '黄土汤',
    meridian: '金匮',
    required: {kQ6: [8], kQ1: [6]},
    extReference: {'hematochezia_after'},
    reference: {kQ2: [10, 3], kQ10: [2]},
    differential: '先便后血＋腹痛喜按 → 脾不统血。',
  ),
  FormulaRule(
    name: '泻心汤',
    meridian: '金匮',
    required: {kQ6: [8], kQ1: [1]},
    extReference: {'hematochezia_before'},
    reference: {kQ3: [2], kQ10: [4]},
    differential: '先血后便＋心烦口渴 → 心火亢盛迫血妄行。',
  ),
  // M. 妇人病
  FormulaRule(
    name: '桂枝茯苓丸',
    meridian: '金匮',
    required: {kQ11: [3, 5]},
    extRequired: {'lesser_abdomen_mass'},
    reference: {kQ2: [6]},
    differential: '妇人宿有癥病＋漏下不止 → 瘀血癥瘕。',
  ),
  FormulaRule(
    name: '胶艾汤',
    meridian: '金匮',
    required: {kQ11: [4, 3], kQ1: [6]},
    reference: {kQ2: [9], kQ10: [2]},
    differential: '妇人漏下或半产后下血不止 → 冲任虚损。',
  ),
  FormulaRule(
    name: '当归芍药散',
    meridian: '金匮',
    required: {kQ5: [6], kQ11: [3, 5]},
    reference: {kQ7: [5], kQ10: [2]},
    differential: '妇人腹中㽲痛 → 肝脾不和血水互结。',
  ),
  FormulaRule(
    name: '干姜人参半夏丸',
    meridian: '金匮',
    required: {kQ12: [4], kQ3: [1, 3]},
    extReference: {'pregnancy'},
    reference: {kQ1: [6], kQ10: [2]},
    differential: '妊娠呕吐不止 → 胃虚寒饮。',
  ),
  FormulaRule(
    name: '当归贝母苦参丸',
    meridian: '金匮',
    required: {kQ7: [5], kQ11: [1]},
    differential: '妊娠小便难 → 血虚热郁。',
  ),
  FormulaRule(
    name: '葵子茯苓散',
    meridian: '金匮',
    required: {kQ7: [5], kQ1: [1]},
    differential: '妊娠有水气身重小便不利。',
  ),
  FormulaRule(
    name: '当归散',
    meridian: '金匮',
    required: {kQ11: [1, 2], kQ1: [1]},
    differential: '妊娠常服 → 养血安胎。',
  ),
  FormulaRule(
    name: '白术散',
    meridian: '金匮',
    required: {kQ11: [1, 2], kQ1: [7]},
    differential: '妊娠养胎 → 偏寒湿。',
  ),
  FormulaRule(
    name: '枳实芍药散',
    meridian: '金匮',
    required: {kQ5: [7]},
    differential: '产后腹痛烦满不得卧 → 气滞血瘀。',
  ),
  FormulaRule(
    name: '下瘀血汤',
    meridian: '金匮',
    required: {kQ5: [7], kQ11: [3]},
    extReference: {'lesser_abdomen_pain'},
    reference: {kQ6: [2]},
    differential: '产后腹痛有干血著脐下 → 瘀血内结。',
  ),
  FormulaRule(
    name: '竹叶汤',
    meridian: '金匮',
    required: {kQ1: [7]},
    reference: {kQ4: [2]},
    differential: '产后中风发热面赤 → 产后正虚感风。',
  ),
  FormulaRule(
    name: '竹皮大丸',
    meridian: '金匮',
    required: {kQ10: [4], kQ1: [1]},
    differential: '妇人乳中虚烦乱呕逆。',
  ),
  FormulaRule(
    name: '温经汤',
    meridian: '金匮',
    required: {kQ11: [3, 4, 5], kQ5: [6]},
    reference: {kQ1: [6, 7, 2], kQ2: [9]},
    differential: '妇人年五十所下利数十日不止＋唇口干燥＋少腹里急 → 冲任虚寒兼瘀。',
  ),
  FormulaRule(
    name: '土瓜根散',
    meridian: '金匮',
    required: {kQ11: [5]},
    extReference: {'lesser_abdomen_pain'},
    differential: '经水不利 → 瘀血。',
  ),
  FormulaRule(
    name: '大黄甘遂汤',
    meridian: '金匮',
    required: {kQ11: [5]},
    extRequired: {'lesser_abdomen_full'},
    differential: '妇人少腹满如敦状＋小便微难 → 水血俱结。',
  ),
  FormulaRule(
    name: '矾石散',
    meridian: '金匮',
    extReference: {'leukorrhea'},
    differential: '经水闭不利＋脏坚癖不止。',
  ),
  FormulaRule(
    name: '红蓝花酒',
    meridian: '金匮',
    required: {kQ11: [3], kQ5: [6]},
    differential: '妇人腹中血气刺痛 → 活血止痛。',
  ),
  FormulaRule(
    name: '蛇床子散',
    meridian: '金匮',
    extReference: {'leukorrhea', 'vulva_cold'},
    differential: '阴寒 → 温阴中坐药。',
  ),
  FormulaRule(
    name: '狼牙汤',
    meridian: '金匮',
    extReference: {'leukorrhea', 'vulva_ulcer'},
    differential: '阴中蚀疮烂。',
  ),
  // N. 杂方
  FormulaRule(
    name: '半夏厚朴汤',
    meridian: '金匮',
    required: {kQ5: [15], kQ10: [2]},
    reference: {kQ8: [8], kQ12: [1, 2]},
    differential: '妇人咽中如有炙脔 → 痰气郁结。',
  ),
  FormulaRule(
    name: '甘麦大枣汤',
    meridian: '金匮',
    required: {kQ10: [4], kQ9: [5]},
    reference: {kQ10: [2]},
    differential: '妇人脏躁喜悲伤欲哭 → 心脾两虚。',
  ),
  FormulaRule(
    name: '三物备急丸',
    meridian: '金匮',
    required: {kQ6: [2]},
    extRequired: {'heart_abdomen_acute'},
    differential: '心腹卒暴百病 → 寒实急证。',
  ),
  FormulaRule(
    name: '天雄散',
    meridian: '金匮',
    required: {kQ1: [6], kQ5: [20], kQ11: [8]},
    reference: {kQ7: [4], kQ10: [2]},
    differential: '阳痿腰冷 → 肾阳虚。',
  ),

  // ===================== 增补方剂（Q12 触发） =====================
  FormulaRule(
    name: '黄芩加半夏生姜汤',
    meridian: '金匮',
    required: {kQ6: [3], kQ12: [2]},
    reference: {kQ2: [4], kQ3: [2]},
    differential: '热利＋干呕 → 太阳少阳合病下利。',
  ),
  FormulaRule(
    name: '大半夏汤',
    meridian: '金匮',
    required: {kQ12: [6]},
    reference: {kQ10: [2], kQ8: [2]},
    differential: '胃反呕吐 → 虚寒胃反。',
  ),
  FormulaRule(
    name: '大黄甘草汤',
    meridian: '金匮',
    required: {kQ12: [5]},
    reference: {kQ6: [2]},
    differential: '食已即吐 → 胃热上冲。与干姜芩连人参汤区别：偏实热便秘。',
  ),
  FormulaRule(
    name: '茯苓泽泻汤',
    meridian: '金匮',
    required: {kQ12: [5]},
    reference: {kQ3: [2], kQ7: [5]},
    differential: '渴欲饮水＋水入则吐 → 与五苓散区别：呕重渴重。',
  ),
];

// ============ 鉴别链（用于同级歧义消解与结果展示） ============
// 每链：key -> 有序方名列表（命中优先取前者）
const Map<String, List<String>> differentialChains = {
  'sweat': ['桂枝加葛根汤', '葛根汤', '桂枝汤', '麻黄汤'], // 有汗/无汗+项背强
  'aversion': ['大青龙汤', '桂枝麻黄各半汤', '葛根汤', '麻黄汤'],
  'pi': ['半夏泻心汤', '大黄黄连泻心汤', '附子泻心汤', '生姜泻心汤', '甘草泻心汤', '旋覆代赭汤'],
  'cold_limbs': ['四逆汤', '通脉四逆汤', '当归四逆汤', '四逆散', '乌梅丸'],
  'jaundice': ['茵陈蒿汤', '栀子柏皮汤', '麻黄连翘赤小豆汤', '栀子大黄汤', '大黄硝石汤', '桂枝加黄芪汤'],
  'abdomen': ['小建中汤', '黄芪建中汤', '理中丸', '当归芍药散', '大承气汤', '白头翁汤', '大建中汤', '大乌头煎', '乌梅丸'],
  'thirst': ['五苓散', '猪苓汤', '白虎汤', '白虎加人参汤', '真武汤', '小青龙汤', '理中丸', '肾气丸', '栝蒌瞿麦丸'],
  'insomnia': ['黄连阿胶汤', '栀子豉汤', '酸枣仁汤', '茯苓四逆汤', '猪苓汤', '炙甘草汤'],
  'menstrual': ['当归四逆汤', '当归芍药散', '胶艾汤', '桂枝茯苓丸', '温经汤', '大黄䗪虫丸'],
  'vomit': ['大黄甘草汤', '干姜黄芩黄连人参汤', '大建中汤', '茯苓泽泻汤', '大半夏汤', '吴茱萸汤', '甘草泻心汤', '旋覆代赭汤', '黄芩加半夏生姜汤', '小半夏汤', '半夏泻心汤', '干姜人参半夏丸'],
};
