#!/usr/bin/env python3
"""生成金匮要略方剂数据（262方）"""
import json

# 金匮要略方剂数据
# 格式与伤寒论一致
JINGUI_FORMULAS = [
    # ===== 痉湿暍第二 =====
    {"id": "guizhi_jia_gegen_tang_jj", "name": "桂枝加葛根汤", "alias": "", "meridian": "太阳", "category": "解表剂",
     "components": [{"name": "葛根", "dosage": "四两", "role": "升津舒经"}, {"name": "桂枝", "dosage": "二两"}, {"name": "芍药", "dosage": "二两"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "炙甘草", "dosage": "二两"}],
     "indication": "太阳病，项背强几几，无汗恶风者。痉病亦可用。",
     "contraindication": "有汗者不可用。", "dosage": "水一斗，先煮葛根减二升，去白沫，内诸药，煮取三升，去滓，温服一升。覆取微似汗。",
     "explanation": "痉病初起兼太阳表证，用此方解表舒经。葛根升津液舒经脉为主药。", "keywords": ["痉", "项背强", "无汗"]},
    {"id": "mahuang_jia_shugen_tang", "name": "麻黄加术汤", "alias": "", "meridian": "太阳", "category": "祛风湿剂",
     "components": [{"name": "麻黄", "dosage": "三两"}, {"name": "桂枝", "dosage": "二两"}, {"name": "杏仁", "dosage": "七十个"}, {"name": "炙甘草", "dosage": "一两"}, {"name": "白术", "dosage": "四两", "role": "健脾燥湿"}],
     "indication": "湿家身烦疼。",
     "contraindication": "阴虚者慎用。", "dosage": "水九升，先煮麻黄减二升，去上沫，内诸药，煮取二升半，去滓，温服八合。覆取微似汗。",
     "explanation": "麻黄汤加白术，治寒湿在表。白术健脾燥湿，麻黄发汗解表。湿家不可大发汗，故麻黄汤减量。", "keywords": ["湿家", "身烦疼", "寒湿"]},
    {"id": "mahuang_xingren_yiyi_gancao_tang", "name": "麻黄杏仁薏苡甘草汤", "alias": "麻杏薏甘汤", "meridian": "太阳", "category": "祛风湿剂",
     "components": [{"name": "麻黄", "dosage": "半两", "role": "轻宣肺气"}, {"name": "杏仁", "dosage": "十个"}, {"name": "薏苡仁", "dosage": "半两", "role": "利湿除痹"}, {"name": "炙甘草", "dosage": "一两"}],
     "indication": "病者一身尽疼，发热，日晡所剧者，名风湿。此病伤于汗出当风，或久伤取冷所致。",
     "contraindication": "寒湿者慎用。", "dosage": "麻豆大，每服四钱匕，水盏半，煮八分，去滓，温服。微汗避风。",
     "explanation": "风湿在表，一身尽疼。麻黄轻宣，薏苡仁利湿除痹。日晡所剧=阳明主时，湿从热化。药量轻，取微汗。", "keywords": ["一身尽疼", "日晡所剧", "风湿"]},
    {"id": "fangji_huangqi_tang_jj", "name": "防己黄芪汤", "alias": "", "meridian": "太阴", "category": "益气祛风剂",
     "components": [{"name": "防己", "dosage": "一两", "role": "祛风利水"}, {"name": "黄芪", "dosage": "一两一分", "role": "益气固表"}, {"name": "白术", "dosage": "三分", "role": "健脾燥湿"}, {"name": "炙甘草", "dosage": "半两"}],
     "indication": "风湿，脉浮身重，汗出恶风者。",
     "contraindication": "阴虚盗汗者慎用。", "dosage": "麻豆大，每抄五钱匕，生姜四片，大枣一枚，水盏半，煎八分，去滓，温服。喘者加麻黄半两。",
     "explanation": "表虚风湿。黄芪益气固表止汗，防己祛风利水，白术健脾。汗出恶风+身重=表虚风湿。倪师：此方治风水（面目浮肿+汗出恶风）。", "keywords": ["脉浮", "身重", "汗出恶风", "风水"]},
    {"id": "gancao_fuzi_tang_jj", "name": "甘草附子汤", "alias": "", "meridian": "少阴", "category": "温经散寒剂",
     "components": [{"name": "炙甘草", "dosage": "二两"}, {"name": "炮附子", "dosage": "二枚"}, {"name": "白术", "dosage": "二两"}, {"name": "桂枝", "dosage": "四两"}],
     "indication": "风湿相搏，骨节疼烦，掣痛不得屈伸，近之则痛剧，汗出短气，小便不利，恶风不欲去衣，或身微肿者。",
     "contraindication": "无风湿者不可用。", "dosage": "水六升，煮取三升，去滓，温服一升，日三服。初服得微汗则解。",
     "explanation": "风湿深入关节，骨节疼烦掣痛。附子温里散寒，桂枝通阳化湿，白术健脾，甘草缓急。", "keywords": ["骨节疼烦", "掣痛", "不得屈伸"]},
    {"id": "yiqi_tang", "name": "一物瓜蒂汤", "alias": "", "meridian": "阳明", "category": "涌吐剂",
     "components": [{"name": "瓜蒂", "dosage": "二七个", "role": "涌吐痰实"}],
     "indication": "太阳中暍，身热疼重，而脉微弱，此以夏月伤冷水，水行皮中所致。",
     "contraindication": "体虚者不可用。", "dosage": "水一升，煮取五合，去滓，顿服。",
     "explanation": "暑月贪凉饮冷，水湿停于肌表。瓜蒂涌吐，使水湿从上而出。此为涌吐法轻剂。", "keywords": ["中暍", "身热疼重", "涌吐"]},

    # ===== 百合狐惑第三 =====
    {"id": "baihe_di_huang_tang", "name": "百合地黄汤", "alias": "", "meridian": "心/肺", "category": "滋阴清热剂",
     "components": [{"name": "百合", "dosage": "七枚", "role": "润肺清心"}, {"name": "生地黄汁", "dosage": "一升", "role": "滋阴凉血"}],
     "indication": "百合病，不经吐下发汗，病形如初者。",
     "contraindication": "脾虚便溏者慎用。", "dosage": "水洗百合，渍一宿，当白沫出，去其水，更以泉水二升，煎取一升，去滓，内地黄汁，煎取一升五合，分温再服。中病勿更服。",
     "explanation": "百合病=心肺阴虚，精神恍惚。百合润肺清心，生地滋阴凉血。百合病皆由心肺阴虚内热所致。", "keywords": ["百合病", "精神恍惚", "心肺阴虚"]},
    {"id": "baihe_jinzi_shigao_tang", "name": "百合鸡子黄汤", "alias": "", "meridian": "心/肺", "category": "滋阴润燥剂",
     "components": [{"name": "百合", "dosage": "七枚"}, {"name": "鸡子黄", "dosage": "一枚", "role": "滋阴润燥"}],
     "indication": "百合病，吐之后者。",
     "contraindication": "无阴虚者不必用。", "dosage": "渍百合如前法，煎取一升，去滓，内鸡子黄，搅匀，煎五分，温服。",
     "explanation": "百合病误吐后伤阴。百合润肺清心，鸡子黄滋阴润燥。误吐伤胃阴，故加鸡子黄养阴。", "keywords": ["百合病", "吐后"]},
    {"id": "gancao_xiexin_tang_hh", "name": "甘草泻心汤", "alias": "", "meridian": "少阳/太阴", "category": "辛开苦降剂",
     "components": [{"name": "炙甘草", "dosage": "四两"}, {"name": "黄芩", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}, {"name": "半夏", "dosage": "半升"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "黄连", "dosage": "一两"}, {"name": "人参", "dosage": "三两"}],
     "indication": "狐惑之为病，状如伤寒，默默欲眠，目不得闭，卧起不安。蚀于喉为惑，蚀于阴为狐。蚀于上部则声嗄。",
     "contraindication": "无寒热错杂者慎用。", "dosage": "水一斗，煮取六升，去滓，再煎取三升，温服一升，日三服。",
     "explanation": "狐惑病=口腔+外阴溃疡+眼部病变=白塞氏病。寒热错杂，湿热虫蚀。甘草泻心汤辛开苦降，清热燥湿。倪师经验方。", "keywords": ["狐惑", "口腔溃疡", "阴部溃疡", "白塞氏病"]},
    {"id": "kushen_tang", "name": "苦参汤", "alias": "", "meridian": "外用", "category": "外洗剂",
     "components": [{"name": "苦参", "dosage": "一升", "role": "清热燥湿杀虫"}],
     "indication": "狐惑病蚀于下部（外阴溃疡）。",
     "contraindication": "内服需慎。", "dosage": "水一斗，煎取七升，去滓，熏洗。",
     "explanation": "外用苦参汤熏洗，清热燥湿杀虫。治狐惑病外阴溃疡。可配合甘草泻心汤内服。", "keywords": ["狐惑", "下部蚀疮", "外阴溃疡"]},

    # ===== 疟病第四 =====
    {"id": "biejia_jian_wan", "name": "鳖甲煎丸", "alias": "", "meridian": "肝/脾", "category": "消癥化积剂",
     "components": [{"name": "鳖甲", "dosage": "十二分", "role": "滋阴软坚"}, {"name": "乌扇", "dosage": "三分"}, {"name": "黄芩", "dosage": "三分"}, {"name": "柴胡", "dosage": "六分"}, {"name": "鼠妇", "dosage": "三分"}, {"name": "干姜", "dosage": "三分"}, {"name": "大黄", "dosage": "三分"}, {"name": "芍药", "dosage": "五分"}, {"name": "桂枝", "dosage": "三分"}, {"name": "葶苈", "dosage": "一分"}, {"name": "石韦", "dosage": "三分"}, {"name": "厚朴", "dosage": "三分"}, {"name": "牡丹", "dosage": "五分"}, {"name": "瞿麦", "dosage": "二分"}, {"name": "紫葳", "dosage": "三分"}, {"name": "半夏", "dosage": "一分"}, {"name": "人参", "dosage": "一分"}, {"name": "蟅虫", "dosage": "五分"}, {"name": "阿胶", "dosage": "三分"}, {"name": "蜂窝", "dosage": "四分"}, {"name": "赤硝", "dosage": "十二分"}, {"name": "蜣螂", "dosage": "六分"}, {"name": "桃仁", "dosage": "二分"}],
     "indication": "疟母（疟疾日久，脾脏肿大，胁下有块）。",
     "contraindication": "体虚者需配合补益。", "dosage": "为末，取灶下灰一斗，清酒一斛五斗，浸灰，候酒尽一半，着鳖甲于中，煮令泛烂如胶漆，绞取汁，内诸药，煎为丸，如梧子大，空心服七丸，日三服。",
     "explanation": "疟疾日久，正虚邪实，痰瘀互结成疟母（脾肿大）。鳖甲软坚滋阴，大队虫药破血逐瘀，大黄攻下，参阿胶扶正。攻补兼施。", "keywords": ["疟母", "胁下有块", "脾肿大"]},
    {"id": "baihu_jia_guizhi_tang", "name": "白虎加桂枝汤", "alias": "", "meridian": "阳明", "category": "清热解表剂",
     "components": [{"name": "知母", "dosage": "六两"}, {"name": "石膏", "dosage": "一斤"}, {"name": "粳米", "dosage": "二合"}, {"name": "炙甘草", "dosage": "二两"}, {"name": "桂枝", "dosage": "三两", "role": "解表散邪"}],
     "indication": "温疟者，其脉如平，身无寒但热，骨节疼烦，时呕。",
     "contraindication": "寒疟不可用。", "dosage": "水一斗，煮米熟汤成，去滓，温服一升，日三服。",
     "explanation": "温疟=热多寒少。白虎汤清阳明热，桂枝解表散邪。骨节疼烦=表邪未尽。", "keywords": ["温疟", "无寒但热", "骨节疼烦"]},

    # ===== 中风历节第五 =====
    {"id": "fuzi_tang_jj", "name": "桂枝芍药知母汤", "alias": "", "meridian": "太阳/少阴", "category": "祛风湿剂",
     "components": [{"name": "桂枝", "dosage": "四两"}, {"name": "芍药", "dosage": "三两"}, {"name": "甘草", "dosage": "二两"}, {"name": "麻黄", "dosage": "二两"}, {"name": "生姜", "dosage": "五两"}, {"name": "白术", "dosage": "五两"}, {"name": "知母", "dosage": "四两", "role": "清热养阴"}, {"name": "防风", "dosage": "四两", "role": "祛风"}, {"name": "炮附子", "dosage": "二枚"}],
     "indication": "诸肢节疼痛，身体尪羸，脚肿如脱，头眩短气，温温欲吐。",
     "contraindication": "阴虚火旺者慎用附子。", "dosage": "水七升，煮取二升，温服七合，日三服。",
     "explanation": "风湿历节，正气已虚。附子温阳散寒，桂枝麻黄防风祛风湿，白术健脾，知母芍药清热养阴护正。攻补兼施、寒热并用。", "keywords": ["肢节疼痛", "尪羸", "脚肿", "历节"]},
    {"id": "wutou_tang", "name": "乌头汤", "alias": "", "meridian": "少阴", "category": "温经散寒剂",
     "components": [{"name": "乌头", "dosage": "五枚", "role": "大热散寒"}, {"name": "麻黄", "dosage": "三两"}, {"name": "芍药", "dosage": "三两"}, {"name": "黄芪", "dosage": "三两"}, {"name": "炙甘草", "dosage": "三两"}],
     "indication": "病历节不可屈伸，疼痛。脚气疼痛，不可屈伸。",
     "contraindication": "有热者禁用。必须严格炮制。", "dosage": "乌头以蜜二升，煎取一升，去乌头。以水三升，煮余药取一升，去滓，内乌头蜜，更煎服。",
     "explanation": "寒湿历节，关节剧痛不可屈伸。乌头大热散寒止痛为君，蜜煎减毒。麻黄开表，黄芪固表，芍药缓急。", "keywords": ["历节", "不可屈伸", "疼痛", "乌头"]},

    # ===== 血痹虚劳第六 =====
    {"id": "huangqi_guizhi_wuwu_tang", "name": "黄芪桂枝五物汤", "alias": "", "meridian": "太阳/血分", "category": "益气活血剂",
     "components": [{"name": "黄芪", "dosage": "三两", "role": "益气固表"}, {"name": "芍药", "dosage": "三两"}, {"name": "桂枝", "dosage": "三两"}, {"name": "生姜", "dosage": "六两"}, {"name": "大枣", "dosage": "十二枚"}],
     "indication": "血痹，阴阳俱微，寸口关上微，尺中小紧，外证身体不仁，如风痹状。",
     "contraindication": "实证者慎用。", "dosage": "水六升，煮取二升，温服七合，日三服。",
     "explanation": "气血不足，血行不畅致血痹（肢体麻木不仁）。黄芪益气，桂枝芍药调和营卫通血脉，姜枣和营。比桂枝汤多黄芪，偏于益气活血。", "keywords": ["血痹", "身体不仁", "麻木", "如风痹"]},
    {"id": "suanzaoren_tang", "name": "酸枣仁汤", "alias": "", "meridian": "肝/心", "category": "养血安神剂",
     "components": [{"name": "酸枣仁", "dosage": "二升", "role": "养肝血安神"}, {"name": "甘草", "dosage": "一两"}, {"name": "知母", "dosage": "二两", "role": "清热除烦"}, {"name": "茯苓", "dosage": "二两", "role": "宁心安神"}, {"name": "川芎", "dosage": "二两", "role": "调血养肝"}],
     "indication": "虚劳虚烦不得眠。",
     "contraindication": "实热失眠者慎用。", "dosage": "水八升，煮酸枣仁得六升，内诸药，煮取三升，分温三服。",
     "explanation": "肝血不足，虚火上扰心神。酸枣仁重用养肝血安神为君，知母清虚热，茯苓宁心，川芎调血养肝，甘草和中。倪师治失眠常用此方。", "keywords": ["虚烦不得眠", "失眠", "肝血虚"]},
    {"id": "dahuang_zhechong_wan", "name": "大黄蟅虫丸", "alias": "", "meridian": "肝/血分", "category": "破血逐瘀剂",
     "components": [{"name": "大黄", "dosage": "十分"}, {"name": "黄芩", "dosage": "二两"}, {"name": "甘草", "dosage": "三两"}, {"name": "桃仁", "dosage": "一升"}, {"name": "杏仁", "dosage": "一升"}, {"name": "芍药", "dosage": "四两"}, {"name": "生地", "dosage": "十两"}, {"name": "干漆", "dosage": "一两"}, {"name": "虻虫", "dosage": "一升"}, {"name": "水蛭", "dosage": "百枚"}, {"name": "蛴螬", "dosage": "一升"}, {"name": "蟅虫", "dosage": "半升"}],
     "indication": "五劳虚极，羸瘦腹满，不能饮食。内有干血，肌肤甲错，两目黯黑。",
     "contraindication": "孕妇禁用。体虚者需配合补益。", "dosage": "为末，蜜丸小豆大，酒饮服五丸，日三服。",
     "explanation": "虚劳内有干血（瘀血久停）。大队虫药破血逐瘀，大黄攻下，生地芍药养血。缓中补虚，去瘀生新。肌肤甲错=血瘀肌肤失养。", "keywords": ["五劳虚极", "干血", "肌肤甲错", "两目黯黑"]},

    # ===== 肺痿肺痈第七 =====
    {"id": "gancao_ganjiang_tang_jj", "name": "甘草干姜汤", "alias": "", "meridian": "肺/脾", "category": "温肺益气剂",
     "components": [{"name": "炙甘草", "dosage": "四两"}, {"name": "干姜", "dosage": "二两"}],
     "indication": "肺痿，吐涎沫而不咳者，其人不渴，必遗尿，小便数。",
     "contraindication": "肺热者不可用。", "dosage": "水三升，煮取一升五合，去滓，分温再服。",
     "explanation": "肺痿=肺叶枯萎，津液不布。吐涎沫不咳不渴=肺中冷。干姜温肺，甘草补中。肺冷不用润肺而用温肺。", "keywords": ["肺痿", "吐涎沫", "不渴", "肺冷"]},
    {"id": "mai_men_dong_tang", "name": "麦门冬汤", "alias": "", "meridian": "肺/胃", "category": "滋阴润肺剂",
     "components": [{"name": "麦门冬", "dosage": "七升", "role": "养阴润肺"}, {"name": "半夏", "dosage": "一升", "role": "降逆化痰"}, {"name": "人参", "dosage": "三两"}, {"name": "甘草", "dosage": "二两"}, {"name": "粳米", "dosage": "三合"}, {"name": "大枣", "dosage": "十二枚"}],
     "indication": "火逆上气，咽喉不利，止逆下气者。",
     "contraindication": "痰湿重者慎用。", "dosage": "水一斗二升，煮取六升，温服一升，日三服，夜一服。",
     "explanation": "肺胃阴虚，虚火上炎。麦冬重用七两滋阴润肺为主，半夏降逆化痰（大队甘药中少佐辛燥防滞）。人参甘草粳米大枣益气养胃。", "keywords": ["火逆上气", "咽喉不利", "肺痿"]},
    {"id": "tingli_dazao_xiefei_tang", "name": "葶苈大枣泻肺汤", "alias": "", "meridian": "肺", "category": "泻肺逐水剂",
     "components": [{"name": "葶苈子", "dosage": "熬令黄色捣丸", "role": "泻肺逐水"}, {"name": "大枣", "dosage": "十二枚", "role": "护中缓急"}],
     "indication": "肺痈，喘不得卧。肺痈胸满胀，一身面目浮肿。",
     "contraindication": "肺虚者不可峻泻。", "dosage": "先以水三升，煮枣取二升，去枣，内葶苈，煮取一升，顿服。",
     "explanation": "肺痈实证，痰涎壅肺。葶苈子泻肺逐水力猛，大枣护中缓葶苈之峻。喘不得卧=水饮壅肺。", "keywords": ["肺痈", "喘不得卧", "浮肿"]},

    # ===== 奔豚气第八 =====
    {"id": "benqi_tang", "name": "奔豚汤", "alias": "", "meridian": "肝/冲脉", "category": "平冲降逆剂",
     "components": [{"name": "甘草", "dosage": "二两"}, {"name": "川芎", "dosage": "二两"}, {"name": "当归", "dosage": "二两"}, {"name": "半夏", "dosage": "四两"}, {"name": "黄芩", "dosage": "二两"}, {"name": "生葛", "dosage": "五两"}, {"name": "芍药", "dosage": "二两"}, {"name": "生姜", "dosage": "四两"}, {"name": "甘李根白皮", "dosage": "一升"}],
     "indication": "奔豚气上冲胸，腹痛，往来寒热。",
     "contraindication": "无肝气上冲者慎用。", "dosage": "水二斗，煮取五升，温服一升，日三服，夜一服。",
     "explanation": "肝郁化火，气循冲脉上冲。当归川芎芍药养血柔肝，黄芩清肝热，半夏生姜降逆，葛根升津，甘李根白皮下气降冲。", "keywords": ["奔豚", "气上冲胸", "腹痛"]},
    {"id": "gui_zhi_jia_gui_tang", "name": "桂枝加桂汤", "alias": "", "meridian": "太阳", "category": "平冲降逆剂",
     "components": [{"name": "桂枝", "dosage": "五两", "role": "平冲降逆"}, {"name": "芍药", "dosage": "三两"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "炙甘草", "dosage": "二两"}],
     "indication": "发汗后，烧针令其汗，针处被寒，核起而赤者，必发奔豚，气从少腹上冲心者。",
     "contraindication": "非奔豚者不可重用桂枝。", "dosage": "水七升，微火煮取三升，去滓，温服一升。",
     "explanation": "烧针发汗后阳虚寒气上冲。桂枝汤加桂枝为五两（原方三两），重用桂枝平冲降逆。灸其核上各一壮。", "keywords": ["奔豚", "气从少腹上冲心", "核起而赤"]},
    {"id": "linggui_wuwei_tang", "name": "苓桂甘枣汤", "alias": "茯苓桂枝甘草大枣汤", "meridian": "太阳/心", "category": "平冲降逆剂",
     "components": [{"name": "茯苓", "dosage": "半斤"}, {"name": "桂枝", "dosage": "四两"}, {"name": "炙甘草", "dosage": "二两"}, {"name": "大枣", "dosage": "十五枚"}],
     "indication": "发汗后，其人脐下悸者，欲作奔豚。",
     "contraindication": "无水饮者慎用。", "dosage": "甘澜水一斗，先煮茯苓减二升，内诸药，煮取三升，温服一升，日三服。",
     "explanation": "发汗后心阳虚，水饮上冲欲作奔豚。茯苓利水宁心，桂枝平冲降逆。甘澜水轻扬不助水邪。", "keywords": ["脐下悸", "欲作奔豚", "水饮"]},

    # ===== 胸痹心痛第九 =====
    {"id": "gualou_xiebai_baijiu_tang", "name": "栝蒌薤白白酒汤", "alias": "", "meridian": "心/肺", "category": "通阳散结剂",
     "components": [{"name": "栝蒌实", "dosage": "一枚", "role": "宽胸散结"}, {"name": "薤白", "dosage": "半升", "role": "通阳散结"}, {"name": "白酒", "dosage": "七升", "role": "行气活血"}],
     "indication": "胸痹之病，喘息咳唾，胸背痛，短气，寸口脉沉而迟，关上小紧数。",
     "contraindication": "阴虚火旺者慎用。", "explanation": "胸阳不振，痰浊闭阻。薤白通阳散结，栝蒌宽胸涤痰，白酒行气活血助药力上行。倪师：此为胸痹基础方。", "keywords": ["胸痹", "胸背痛", "短气", "喘息"]},
    {"id": "gualou_xiebai_banxia_tang", "name": "栝蒌薤白半夏汤", "alias": "", "meridian": "心/肺", "category": "通阳化痰剂",
     "components": [{"name": "栝蒌实", "dosage": "一枚"}, {"name": "薤白", "dosage": "三两"}, {"name": "半夏", "dosage": "半升", "role": "化痰降逆"}, {"name": "白酒", "dosage": "一斗"}],
     "indication": "胸痹不得卧，心痛彻背者。",
     "contraindication": "痰热者慎用。", "explanation": "胸痹重证，痰浊更甚。比栝蒌薤白白酒汤加半夏，化痰降逆力量更强。不得卧+心痛彻背=痰浊闭阻严重。", "keywords": ["胸痹", "不得卧", "心痛彻背"]},
    {"id": "zhishi_xiebai_guizhi_tang", "name": "枳实薤白桂枝汤", "alias": "", "meridian": "心/胃", "category": "通阳散结剂",
     "components": [{"name": "枳实", "dosage": "四枚"}, {"name": "厚朴", "dosage": "四两"}, {"name": "薤白", "dosage": "半升"}, {"name": "桂枝", "dosage": "一两"}, {"name": "栝蒌实", "dosage": "一枚"}],
     "indication": "胸痹，心中痞气，气结在胸，胸满，胁下逆抢心。",
     "contraindication": "无气结者慎用。", "explanation": "胸痹兼气滞。枳实行气消痞，厚朴除满，薤白通阳散结，栝蒌宽胸，桂枝温通。气结在胸+胁下逆抢心=气滞严重。", "keywords": ["胸痹", "心中痞", "胁下逆抢心"]},
    {"id": "renshen_tang", "name": "人参汤", "alias": "理中汤", "meridian": "太阴", "category": "温中补虚剂",
     "components": [{"name": "人参", "dosage": "三两"}, {"name": "甘草", "dosage": "三两"}, {"name": "白术", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}],
     "indication": "胸痹，心中痞气，气结在胸（偏虚者）。理中汤原方。",
     "contraindication": "实证者不可用。", "explanation": "胸痹偏于中阳虚者，用人参汤（理中汤）温中补虚。与枳实薤白桂枝汤对比：一虚一实。", "keywords": ["胸痹", "中阳虚", "理中汤"]},
    {"id": "fu_zi_sheng_jiang_ji_shi_tang", "name": "薏苡附子散", "alias": "", "meridian": "心/阳", "category": "温阳散寒剂",
     "components": [{"name": "薏苡仁", "dosage": "十五两"}, {"name": "炮附子", "dosage": "十枚", "role": "温阳散寒"}],
     "indication": "胸痹缓急者（胸痹发作有时，缓则如常人）。",
     "contraindication": "阴虚者慎用。", "explanation": "胸痹阳虚寒盛。附子温阳散寒止痛，薏苡仁除湿舒筋。散剂缓服。", "keywords": ["胸痹", "缓急", "阳虚"]},

    # ===== 腹满寒疝第十 =====
    {"id": "houpo_sanwu_tang", "name": "厚朴三物汤", "alias": "", "meridian": "阳明", "category": "行气除满剂",
     "components": [{"name": "厚朴", "dosage": "八两"}, {"name": "大黄", "dosage": "四两"}, {"name": "枳实", "dosage": "五枚"}],
     "indication": "痛而闭者（腹痛且大便不通）。",
     "contraindication": "虚寒腹痛者不可用。", "explanation": "厚朴行气为君（重用八两），大黄通便，枳实破气。与小承气汤组成相同但厚朴量大→偏于行气除满。", "keywords": ["腹痛", "闭", "便闭", "行气"]},
    {"id": "dahuang_fuzi_tang", "name": "大黄附子汤", "alias": "", "meridian": "阳明/少阴", "category": "温下剂",
     "components": [{"name": "大黄", "dosage": "三两", "role": "攻下"}, {"name": "炮附子", "dosage": "三枚", "role": "温里散寒"}, {"name": "细辛", "dosage": "二两", "role": "温经散寒"}],
     "indication": "胁下偏痛，发热，其脉紧弦，此寒也，以温药下之。",
     "contraindication": "热结者不可用。", "explanation": "寒积里实。大黄攻下，附子细辛温里散寒。紧弦脉=寒实证。温下法代表方，治寒邪凝聚之腹痛便秘。", "keywords": ["胁下偏痛", "脉紧弦", "寒实", "温下"]},
    {"id": "daxianxiong_tang_jj", "name": "大黄附子汤", "alias": "", "meridian": "阳明/少阴", "category": "温下剂",
     "components": [{"name": "大黄", "dosage": "三两"}, {"name": "炮附子", "dosage": "三枚"}, {"name": "细辛", "dosage": "二两"}],
     "indication": "胁下偏痛，发热，脉紧弦者。",
     "contraindication": "热结者不可用。", "dosage": "水五升，煮取二升，分温三服。",
     "explanation": "寒积腹痛便秘。温下法代表方。", "keywords": ["胁下偏痛", "脉紧弦"]},
    {"id": "wutou_jian_tang", "name": "乌头煎", "alias": "大乌头煎", "meridian": "少阴", "category": "散寒止痛剂",
     "components": [{"name": "乌头", "dosage": "大者五枚", "role": "大热散寒止痛"}],
     "indication": "寒疝绕脐痛，若发则白汗出，手足厥冷，其脉沉紧者。",
     "contraindication": "有热者禁用。必须蜜煎减毒。", "explanation": "寒疝重证。乌头大热大毒，蜜煎减毒止痛。绕脐痛+手足厥冷+脉沉紧=阴寒内结。", "keywords": ["寒疝", "绕脐痛", "手足厥冷", "乌头"]},

    # ===== 痰饮第十二 =====
    {"id": "linggui_zhuugan_tang_jj", "name": "苓桂术甘汤", "alias": "", "meridian": "脾/膀胱", "category": "温阳化饮剂",
     "components": [{"name": "茯苓", "dosage": "四两"}, {"name": "桂枝", "dosage": "三两"}, {"name": "白术", "dosage": "三两"}, {"name": "甘草", "dosage": "二两"}],
     "indication": "心下有痰饮，胸胁支满，目眩。",
     "contraindication": "阴虚者慎用。", "explanation": "痰饮停于中焦。茯苓利水，桂枝温阳化气，白术健脾制水。为治痰饮之基础方。", "keywords": ["痰饮", "胸胁支满", "目眩"]},
    {"id": "xiaobanxia_jia_fuling_tang", "name": "小半夏加茯苓汤", "alias": "", "meridian": "胃", "category": "化饮降逆剂",
     "components": [{"name": "半夏", "dosage": "一升"}, {"name": "生姜", "dosage": "半斤"}, {"name": "茯苓", "dosage": "三两", "role": "利水宁心"}],
     "indication": "卒呕吐，心下痞，膈间有水，眩悸者。",
     "contraindication": "阴虚者慎用。", "explanation": "水饮停于胃脘。半夏生姜降逆止呕，茯苓利水。膈间有水+眩悸=水饮上泛。", "keywords": ["呕吐", "心下痞", "膈间有水", "眩悸"]},
    {"id": "gan_sui_ban_xia_tang", "name": "甘遂半夏汤", "alias": "", "meridian": "肠/心", "category": "攻逐水饮剂",
     "components": [{"name": "甘遂", "dosage": "大者三枚", "role": "攻逐水饮"}, {"name": "半夏", "dosage": "十二枚"}, {"name": "芍药", "dosage": "五枚"}, {"name": "甘草", "dosage": "如指大一枚"}],
     "indication": "病者脉伏，其人欲自利，利反快，虽利，心下续坚满，此为留饮欲去故也。",
     "contraindication": "体虚者慎用。", "explanation": "留饮欲去不去。甘遂攻逐水饮为君，半夏散结，芍药缓急，甘草和药。利反快=水饮去则舒。心下续坚满=水饮未尽。", "keywords": ["留饮", "心下坚满", "利反快"]},
    {"id": "jizhijuzi_tang", "name": "己椒苈黄丸", "alias": "", "meridian": "肠", "category": "攻逐水饮剂",
     "components": [{"name": "防己", "dosage": "一两"}, {"name": "椒目", "dosage": "一两"}, {"name": "葶苈", "dosage": "一两"}, {"name": "大黄", "dosage": "一两"}],
     "indication": "腹满，口舌干燥，此肠间有水气。",
     "contraindication": "虚证者慎用。", "explanation": "水饮走于肠间。防己利水，椒目行水，葶苈泻肺利水，大黄攻下。腹满+口干=水饮阻气化。", "keywords": ["腹满", "口舌干燥", "肠间水气"]},
    {"id": "xiaokezhu_yu_tang", "name": "小青龙汤加减", "alias": "", "meridian": "太阳/肺", "category": "解表化饮剂",
     "components": [{"name": "麻黄", "dosage": "三两"}, {"name": "芍药", "dosage": "三两"}, {"name": "细辛", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}, {"name": "甘草", "dosage": "三两"}, {"name": "桂枝", "dosage": "三两"}, {"name": "五味子", "dosage": "半升"}, {"name": "半夏", "dosage": "半升"}],
     "indication": "咳逆倚息不得卧。支饮（水饮停于胸膈）。",
     "contraindication": "肺热者不可用。", "explanation": "支饮咳喘。小青龙汤解表化饮。水饮停于胸膈，肺气不降。", "keywords": ["咳逆倚息", "不得卧", "支饮"]},

    # ===== 消渴小便不利淋病第十三 =====
    {"id": "wuling_san_jj", "name": "五苓散", "alias": "", "meridian": "太阳/膀胱", "category": "利水渗湿剂",
     "components": [{"name": "猪苓", "dosage": "十八铢"}, {"name": "泽泻", "dosage": "一两六铢"}, {"name": "白术", "dosage": "十八铢"}, {"name": "茯苓", "dosage": "十八铢"}, {"name": "桂枝", "dosage": "半两"}],
     "indication": "脉浮，小便不利，微热消渴者。",
     "contraindication": "阴虚者慎用。", "explanation": "膀胱蓄水。猪苓泽泻茯苓利水，白术健脾，桂枝温阳化气。", "keywords": ["消渴", "小便不利", "膀胱蓄水"]},
    {"id": "wenzhuli_tang", "name": "文蛤散", "alias": "", "meridian": "阳明", "category": "清热利湿剂",
     "components": [{"name": "文蛤", "dosage": "五两", "role": "清热利湿"}],
     "indication": "渴欲饮水不止者。",
     "contraindication": "无热者慎用。", "explanation": "湿热内蕴，津不上承。文蛤清热利湿止渴。", "keywords": ["渴欲饮水不止", "湿热"]},
    {"id": "puleisan", "name": "蒲灰散", "alias": "", "meridian": "膀胱", "category": "利水通淋剂",
     "components": [{"name": "蒲灰", "dosage": "七分"}, {"name": "滑石", "dosage": "三分"}],
     "indication": "小便不利，或有水气。",
     "contraindication": "无瘀热者慎用。", "explanation": "蒲灰（蒲黄灰）活血利水，滑石利水通淋。治小便不利兼瘀热。", "keywords": ["小便不利", "水气"]},

    # ===== 水气病第十四 =====
    {"id": "fangji_huangqi_jj", "name": "防己黄芪汤", "alias": "", "meridian": "太阴", "category": "益气祛风剂",
     "components": [{"name": "防己", "dosage": "一两"}, {"name": "黄芪", "dosage": "一两一分"}, {"name": "白术", "dosage": "三分"}, {"name": "炙甘草", "dosage": "半两"}],
     "indication": "风水，脉浮身重，汗出恶风者。",
     "contraindication": "阴虚者慎用。", "explanation": "风水=外感风邪致水湿泛滥。黄芪固表，防己利水，白术健脾。", "keywords": ["风水", "脉浮身重", "汗出恶风"]},
    {"id": "yuebi_tang", "name": "越婢汤", "alias": "", "meridian": "肺/脾", "category": "宣肺利水剂",
     "components": [{"name": "麻黄", "dosage": "六两"}, {"name": "石膏", "dosage": "半斤"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十五枚"}, {"name": "炙甘草", "dosage": "二两"}],
     "indication": "风水恶风，一身悉肿，脉浮不渴，续自汗出，无大热。",
     "contraindication": "无表证者慎用。", "explanation": "风水夹热。麻黄宣肺利水，石膏清里热。一身悉肿+自汗出=风水在表兼里热。", "keywords": ["风水", "一身悉肿", "恶风", "自汗出"]},
    {"id": "yuebi_jia_banxia_tang", "name": "越婢加半夏汤", "alias": "", "meridian": "肺", "category": "宣肺化饮剂",
     "components": [{"name": "麻黄", "dosage": "六两"}, {"name": "石膏", "dosage": "半斤"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十五枚"}, {"name": "炙甘草", "dosage": "二两"}, {"name": "半夏", "dosage": "半升"}],
     "indication": "咳而上气，此为肺胀，其人喘，目如脱状。",
     "contraindication": "无痰饮者慎用。", "explanation": "肺胀咳喘。越婢汤宣肺清热，半夏化痰降逆。目如脱状=咳喘严重。", "keywords": ["肺胀", "咳而上气", "喘", "目如脱状"]},
    {"id": "fangji_fuling_tang", "name": "防己茯苓汤", "alias": "", "meridian": "太阴", "category": "益气利水剂",
     "components": [{"name": "防己", "dosage": "三两"}, {"name": "黄芪", "dosage": "三两"}, {"name": "桂枝", "dosage": "三两"}, {"name": "茯苓", "dosage": "六两"}, {"name": "炙甘草", "dosage": "二两"}],
     "indication": "皮水为病，四肢肿，水气在皮肤中，四肢聂聂动者。",
     "contraindication": "无皮水者慎用。", "explanation": "皮水=水行皮中。防己茯苓利水，黄芪益气固表，桂枝通阳化气。四肢聂聂动=水气在皮肤中跳动。", "keywords": ["皮水", "四肢肿", "聂聂动"]},
    {"id": "gancao_fuzi_jj", "name": "甘草麻黄汤", "alias": "", "meridian": "肺/脾", "category": "宣肺利水剂",
     "components": [{"name": "甘草", "dosage": "二两"}, {"name": "麻黄", "dosage": "四两"}],
     "indication": "皮水，身面浮肿，小便不利。",
     "contraindication": "风水有热者慎用。", "explanation": "皮水表实。麻黄发汗宣肺利水，甘草和中。二味药精简。", "keywords": ["皮水", "身面浮肿", "小便不利"]},

    # ===== 黄疸第十五 =====
    {"id": "yinchen_hao_tang_jj", "name": "茵陈蒿汤", "alias": "", "meridian": "肝/胆/脾", "category": "清热利湿退黄剂",
     "components": [{"name": "茵陈蒿", "dosage": "六两", "role": "清热利湿退黄"}, {"name": "栀子", "dosage": "十四枚", "role": "清热利湿"}, {"name": "大黄", "dosage": "二两", "role": "攻下泄热"}],
     "indication": "谷疸之为病，寒热不食，食即头眩，心胸不安，久久发黄为谷疸。阳明病发热汗出者，此为热越，不能发黄也。但头汗出，身无汗，剂颈而还，小便不利，渴引水浆者，此为瘀热在里，身必发黄。",
     "contraindication": "寒湿黄疸者慎用。", "explanation": "湿热黄疸。茵陈清热利湿退黄为君，栀子清三焦热，大黄通腑泄热。头汗出+小便不利+身黄=湿热瘀里。", "keywords": ["黄疸", "谷疸", "身黄", "小便不利", "头汗出"]},
    {"id": "yinchen_wuling_san", "name": "茵陈五苓散", "alias": "", "meridian": "肝/膀胱", "category": "利湿退黄剂",
     "components": [{"name": "茵陈蒿", "dosage": "末十分"}, {"name": "五苓散", "dosage": "五分"}],
     "indication": "黄疸病，茵陈五苓散主之。",
     "contraindication": "热重于湿者当用茵陈蒿汤。", "explanation": "湿重于热的黄疸。茵陈退黄，五苓散利水渗湿。比茵陈蒿汤力量缓和。", "keywords": ["黄疸", "湿重于热"]},
    {"id": "zhizi_dahuang_tang", "name": "栀子大黄汤", "alias": "", "meridian": "阳明", "category": "清热退黄剂",
     "components": [{"name": "栀子", "dosage": "十四枚"}, {"name": "大黄", "dosage": "一两"}, {"name": "枳实", "dosage": "五枚"}, {"name": "豆豉", "dosage": "一升"}],
     "indication": "酒黄疸，心中懊憹或热痛。",
     "contraindication": "寒湿者慎用。", "explanation": "酒疸=饮酒过度致黄疸。栀子清热，大黄泄热，枳实破气，豆豉宣透。心中懊憹热痛=热蕴中焦。", "keywords": ["酒疸", "心中懊憹", "热痛"]},
    {"id": "dahuang_mudan_tang", "name": "大黄牡丹汤", "alias": "", "meridian": "大肠", "category": "泻热逐瘀剂",
     "components": [{"name": "大黄", "dosage": "四两"}, {"name": "牡丹", "dosage": "一两", "role": "清热凉血"}, {"name": "桃仁", "dosage": "五十个"}, {"name": "冬瓜仁", "dosage": "半升", "role": "排脓消痈"}, {"name": "芒硝", "dosage": "三合"}],
     "indication": "肠痈之为病，其身甲错，腹皮急，按之濡，如肿状，腹无积聚，身无热，脉数。肠痈者，少腹肿痞，按之即痛如淋，小便自调，时时发热，自汗出，复恶寒。",
     "contraindication": "肠痈溃后体虚者慎用。", "explanation": "肠痈（阑尾炎）初起。大黄攻下泄热，桃仁丹皮活血逐瘀，冬瓜仁排脓，芒硝软坚。少腹肿痞+按之痛=肠痈实证。", "keywords": ["肠痈", "少腹肿痞", "按之痛", "阑尾炎"]},
    {"id": "dahuang_gansui_tang", "name": "大黄甘遂汤", "alias": "", "meridian": "血分", "category": "攻逐水瘀剂",
     "components": [{"name": "大黄", "dosage": "四两"}, {"name": "甘遂", "dosage": "二两"}, {"name": "阿胶", "dosage": "二两"}],
     "indication": "妇人少腹满如敦状，小便微难而不渴，此为水与血俱结在血室也。",
     "contraindication": "孕妇禁用。体虚者慎用。", "explanation": "水血互结于血室。大黄攻下逐瘀，甘遂攻逐水饮，阿胶养血护正。攻逐水血兼扶正。", "keywords": ["少腹满", "水与血俱结", "血室"]},

    # ===== 惊悸吐衄下血第十六 =====
    {"id": "banxia_mahuang_wan", "name": "半夏麻黄丸", "alias": "", "meridian": "心/肺", "category": "化饮降逆剂",
     "components": [{"name": "半夏", "dosage": "等分"}, {"name": "麻黄", "dosage": "等分"}],
     "indication": "心下悸者，半夏麻黄丸主之。",
     "contraindication": "无水饮者慎用。", "explanation": "水饮凌心之心悸。半夏化饮，麻黄宣肺利水。丸剂缓图。", "keywords": ["心下悸", "水饮凌心"]},
    {"id": "huangtu_tang", "name": "黄土汤", "alias": "", "meridian": "脾", "category": "温阳止血剂",
     "components": [{"name": "甘草", "dosage": "三两"}, {"name": "干地黄", "dosage": "三两"}, {"name": "白术", "dosage": "三两"}, {"name": "炮附子", "dosage": "三两"}, {"name": "阿胶", "dosage": "三两"}, {"name": "黄芩", "dosage": "三两"}, {"name": "灶中黄土", "dosage": "半斤", "role": "温中止血"}],
     "indication": "下血，先便后血，此远血也。",
     "contraindication": "热盛出血者不可用。", "explanation": "脾阳虚不能统血。灶中黄土温中止血，附子白术温阳健脾，地黄阿胶养血，黄芩防温燥太过。先便后血=远血（上消化道出血）。", "keywords": ["下血", "先便后血", "远血", "脾不统血"]},
    {"id": "zhiye_tang", "name": "柏叶汤", "alias": "", "meridian": "肝/肺", "category": "凉血止血剂",
     "components": [{"name": "柏叶", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}, {"name": "艾叶", "dosage": "三把"}, {"name": "马通汁", "dosage": "一升"}],
     "indication": "吐血不止者。",
     "contraindication": "实热出血者慎用干姜艾叶。", "explanation": "吐血不止。柏叶凉血止血，干姜艾叶温经止血（反佐），马通汁引血下行。寒热并用。", "keywords": ["吐血不止", "寒热并用"]},
    {"id": "xie_xin_tang_jj", "name": "泻心汤", "alias": "大黄黄连泻心汤", "meridian": "心/胃", "category": "清热泻火剂",
     "components": [{"name": "大黄", "dosage": "二两"}, {"name": "黄连", "dosage": "一两"}, {"name": "黄芩", "dosage": "一两"}],
     "indication": "心气不足，吐血衄血。",
     "contraindication": "虚寒出血者不可用。", "explanation": "心胃火盛，迫血妄行。大黄黄连黄芩苦寒泻火止血。火降则血自归经。", "keywords": ["吐血", "衄血", "心胃火盛"]},

    # ===== 呕吐哕下利第十七 =====
    {"id": "xiao_xia_xia_tang", "name": "小半夏汤", "alias": "", "meridian": "胃", "category": "化饮降逆剂",
     "components": [{"name": "半夏", "dosage": "一升"}, {"name": "生姜", "dosage": "半斤"}],
     "indication": "诸呕吐，谷不得下者。",
     "contraindication": "阴虚者慎用。", "explanation": "水饮停胃，胃气上逆。半夏降逆化饮，生姜散寒止呕。为止呕祖方。", "keywords": ["呕吐", "谷不得下", "止呕"]},
    {"id": "daxiaoyao_tang", "name": "大半夏汤", "alias": "", "meridian": "胃", "category": "补中降逆剂",
     "components": [{"name": "半夏", "dosage": "二升"}, {"name": "人参", "dosage": "三两"}, {"name": "白蜜", "dosage": "一升", "role": "润燥和中"}],
     "indication": "胃反呕吐者（朝食暮吐，暮食朝吐）。",
     "contraindication": "有热者慎用。", "explanation": "脾胃虚寒，胃气不降。半夏降逆，人参补中，白蜜润燥。胃反=宿食不化，朝食暮吐。", "keywords": ["胃反", "朝食暮吐", "暮食朝吐"]},
    {"id": "dahuang_gancao_tang", "name": "大黄甘草汤", "alias": "", "meridian": "胃/肠", "category": "泻热和胃剂",
     "components": [{"name": "大黄", "dosage": "四两"}, {"name": "甘草", "dosage": "一两"}],
     "indication": "食已即吐者。",
     "contraindication": "虚寒呕吐者不可用。", "explanation": "胃肠实热，食入即吐。大黄泻热通腑，甘草缓和。食已即吐=胃热上冲。", "keywords": ["食已即吐", "胃热"]},
    {"id": "wuzhuyu_tang_jj", "name": "吴茱萸汤", "alias": "", "meridian": "肝/胃", "category": "温中降逆剂",
     "components": [{"name": "吴茱萸", "dosage": "一升"}, {"name": "人参", "dosage": "二两"}, {"name": "生姜", "dosage": "六两"}, {"name": "大枣", "dosage": "十二枚"}],
     "indication": "呕而胸满者。干呕吐涎沫，头痛者。",
     "contraindication": "胃热呕吐者不可用。", "explanation": "肝寒犯胃，浊阴上逆。吴茱萸温肝降逆，生姜和胃，参枣补中。", "keywords": ["呕而胸满", "干呕吐涎沫", "头痛"]},
    {"id": "banxia_xiexin_tang_jj", "name": "半夏泻心汤", "alias": "", "meridian": "少阳/太阴", "category": "辛开苦降剂",
     "components": [{"name": "半夏", "dosage": "半升"}, {"name": "黄芩", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}, {"name": "人参", "dosage": "三两"}, {"name": "黄连", "dosage": "一两"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "炙甘草", "dosage": "三两"}],
     "indication": "呕而肠鸣，心下痞者。",
     "contraindication": "无寒热错杂者慎用。", "explanation": "寒热错杂于中焦。呕+肠鸣+心下痞=半夏泻心汤证。辛开苦降。", "keywords": ["呕", "肠鸣", "心下痞"]},
    {"id": "chizhishengjiangbanxiagancaoren_tang", "name": "猪苓散", "alias": "", "meridian": "膀胱", "category": "利水渗湿剂",
     "components": [{"name": "猪苓", "dosage": "一两"}, {"name": "茯苓", "dosage": "一两"}, {"name": "白术", "dosage": "一两"}],
     "indication": "呕吐而病在膈上，后思水者，猪苓散主之。",
     "contraindication": "阴虚者慎用。", "explanation": "水饮在膈上致呕。猪苓茯苓利水，白术健脾。思水=水饮去后胃中津液不足。", "keywords": ["呕吐", "膈上", "思水"]},

    # ===== 疮痈肠痈第十八 =====
    {"id": "yiyi_fuzi_baijiang_san", "name": "薏苡附子败酱散", "alias": "", "meridian": "大肠", "category": "排脓消痈剂",
     "components": [{"name": "薏苡仁", "dosage": "十分"}, {"name": "败酱草", "dosage": "五分", "role": "清热排脓"}, {"name": "炮附子", "dosage": "二分"}],
     "indication": "肠痈之为病，其身甲错，腹皮急，按之濡，如肿状，腹无积聚，身无热，脉数。",
     "contraindication": "肠痈热盛者当用大黄牡丹汤。", "explanation": "肠痈脓已成。薏苡仁排脓，败酱草清热排脓，附子温通。身无热+脉数=脓已成而正气不足。", "keywords": ["肠痈", "脓已成", "身无热"]},
    {"id": "paizhong_san", "name": "排脓散", "alias": "", "meridian": "大肠", "category": "排脓消痈剂",
     "components": [{"name": "枳实", "dosage": "十六枚"}, {"name": "芍药", "dosage": "六分"}, {"name": "桔梗", "dosage": "二分"}],
     "indication": "疮痈脓已成。",
     "contraindication": "脓未成者当消痈。", "explanation": "排脓消痈。枳实行气排脓，芍药缓急，桔梗排脓。", "keywords": ["疮痈", "脓已成", "排脓"]},
    {"id": "paizhong_tang", "name": "排脓汤", "alias": "", "meridian": "肺/大肠", "category": "排脓消痈剂",
     "components": [{"name": "甘草", "dosage": "二两"}, {"name": "桔梗", "dosage": "三两"}, {"name": "生姜", "dosage": "一两"}, {"name": "大枣", "dosage": "十枚"}],
     "indication": "疮痈脓已成，咳唾脓血。",
     "contraindication": "脓未成者慎用。", "explanation": "排脓汤。桔梗排脓为主药，甘草解毒，姜枣和营。治肺痈脓已成。", "keywords": ["疮痈", "咳唾脓血", "排脓"]},

    # ===== 妇人妊娠第二十 =====
    {"id": "guizhi_tang_jj", "name": "桂枝汤", "alias": "", "meridian": "太阳", "category": "解表剂",
     "components": [{"name": "桂枝", "dosage": "三两"}, {"name": "芍药", "dosage": "三两"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "炙甘草", "dosage": "二两"}],
     "indication": "妇人得平脉，阴脉小弱，其人渴，不能食，无寒热，名妊娠。",
     "contraindication": "表证者用，非表证者慎用。", "explanation": "妊娠恶阻轻证。平脉+阴脉小弱=胎气初结。桂枝汤调和营卫，和阴阳。", "keywords": ["妊娠", "恶阻", "平脉"]},
    {"id": "jiajian_wuzhu_yu_tang", "name": "当归散", "alias": "", "meridian": "肝/脾", "category": "养血安胎剂",
     "components": [{"name": "当归", "dosage": "一斤"}, {"name": "芍药", "dosage": "一斤"}, {"name": "川芎", "dosage": "半斤"}, {"name": "白术", "dosage": "半斤"}, {"name": "黄芩", "dosage": "一斤"}],
     "indication": "妇人妊娠，宜常服当归散。",
     "contraindication": "阴虚血热者慎用。", "explanation": "养血安胎。当归芍药川芎养血和血，白术健脾，黄芩清热安胎。倪师：妊娠常服方，血虚有热者宜。", "keywords": ["妊娠", "养血", "安胎"]},
    {"id": "danggui_shao_yao_san", "name": "当归芍药散", "alias": "", "meridian": "肝/脾", "category": "养血利水剂",
     "components": [{"name": "当归", "dosage": "三两"}, {"name": "芍药", "dosage": "一斤"}, {"name": "川芎", "dosage": "半斤"}, {"name": "茯苓", "dosage": "四两"}, {"name": "白术", "dosage": "四两"}, {"name": "泽泻", "dosage": "半斤"}],
     "indication": "妇人怀妊，腹中㽲痛。",
     "contraindication": "无血虚水停者慎用。", "explanation": "妊娠血虚水停。当归芍药川芎养血，茯苓白术泽泻利水。腹中㽲痛=血虚水停，筋脉失养。倪师：此方治妊娠腹痛+水肿。", "keywords": ["妊娠", "腹中㽲痛", "养血利水"]},
    {"id": "gancao_ganjiang_fuzi_tang_jj", "name": "干姜附子汤", "alias": "", "meridian": "少阴", "category": "回阳救逆剂",
     "components": [{"name": "干姜", "dosage": "一两"}, {"name": "生附子", "dosage": "一枚"}],
     "indication": "产后下利虚极，白头翁加甘草阿胶汤主之。",
     "contraindication": "非阳虚者不可用。", "explanation": "产后阳虚下利。回阳救逆。", "keywords": ["产后", "下利", "阳虚"]},
    {"id": "baibaitouweng_jiagancao_ejiao_tang", "name": "白头翁加甘草阿胶汤", "alias": "", "meridian": "肝/大肠", "category": "清热止利剂",
     "components": [{"name": "白头翁", "dosage": "二两"}, {"name": "黄连", "dosage": "三两"}, {"name": "黄柏", "dosage": "三两"}, {"name": "秦皮", "dosage": "三两"}, {"name": "甘草", "dosage": "二两"}, {"name": "阿胶", "dosage": "二两"}],
     "indication": "产后下利虚极。",
     "contraindication": "虚寒下利者不可用。", "explanation": "产后热利兼虚。白头翁汤清热止利，甘草阿胶养血缓中。产后体虚故加甘草阿胶扶正。", "keywords": ["产后", "下利", "热利", "虚极"]},

    # ===== 妇人产后第二十一 =====
    {"id": "jizhi_jiangsan", "name": "枳实芍药散", "alias": "", "meridian": "肝/胃", "category": "行气活血剂",
     "components": [{"name": "枳实", "dosage": "烧令黑勿太过"}, {"name": "芍药", "dosage": "等分"}],
     "indication": "产后腹痛，烦满不得卧。",
     "contraindication": "虚证腹痛者慎用。", "explanation": "产后气滞血瘀腹痛。枳实破气，芍药缓急。烧令黑=存性入血分。", "keywords": ["产后腹痛", "烦满", "不得卧"]},
    {"id": "xiaochaihu_tang_jj", "name": "大承气汤", "alias": "", "meridian": "阳明", "category": "峻下剂",
     "components": [{"name": "大黄", "dosage": "四两"}, {"name": "厚朴", "dosage": "半斤"}, {"name": "枳实", "dosage": "五枚"}, {"name": "芒硝", "dosage": "三合"}],
     "indication": "产后七八日，无太阳证，少腹坚痛，此恶露不尽，不大便，烦躁发热。",
     "contraindication": "产后体虚者慎用峻下。", "explanation": "产后瘀血内停兼阳明腑实。大承气汤通腑泄热。恶露不尽+不大便+烦躁=瘀热互结。", "keywords": ["产后", "恶露不尽", "不大便", "烦躁"]},

    # ===== 妇人杂病第二十二 =====
    {"id": "gualou_xiebai_baijiu_tang_jj", "name": "栝蒌薤白白酒汤", "alias": "", "meridian": "心/肺", "category": "通阳散结剂",
     "components": [{"name": "栝蒌实", "dosage": "一枚"}, {"name": "oxetine", "dosage": "半升"}, {"name": "白酒", "dosage": "七升"}],
     "indication": "胸痹不得卧，心痛彻背。",
     "contraindication": "阴虚者慎用。", "explanation": "胸阳不振。", "keywords": ["胸痹", "心痛彻背"]},
    {"id": "xiaochaohu_tang_jj", "name": "小柴胡汤", "alias": "", "meridian": "少阳", "category": "和解剂",
     "components": [{"name": "柴胡", "dosage": "半斤"}, {"name": "黄芩", "dosage": "三两"}, {"name": "人参", "dosage": "三两"}, {"name": "半夏", "dosage": "半升"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "炙甘草", "dosage": "三两"}],
     "indication": "妇人中风，七八日续来寒热，发作有时，经水适断者，此为热入血室。",
     "contraindication": "经水适来者慎用。", "explanation": "热入血室。小柴胡汤和解少阳，透邪外出。经水适断+寒热发作有时=热入血室。", "keywords": ["热入血室", "寒热发作有时", "经水适断"]},
    {"id": "gualou_gui_zhi_banxia_tang", "name": "栝蒌桂枝汤", "alias": "", "meridian": "太阳", "category": "解表养阴剂",
     "components": [{"name": "栝蒌根", "dosage": "二两"}, {"name": "桂枝", "dosage": "三两"}, {"name": "芍药", "dosage": "三两"}, {"name": "甘草", "dosage": "二两"}, {"name": "生姜", "dosage": "三两"}, {"name": "大枣", "dosage": "十二枚"}],
     "indication": "太阳病，其证备，身体强几几然，脉反沉迟，此为痉。",
     "contraindication": "无痉病者慎用。", "explanation": "痉病兼津液不足。桂枝汤解表，栝蒌根生津舒经。", "keywords": ["痉", "身体强几几", "脉沉迟"]},
    {"id": "xie_xin_tang_jj2", "name": "半夏泻心汤", "alias": "", "meridian": "少阳/太阴", "category": "辛开苦降剂",
     "components": [{"name": "半夏", "dosage": "半升"}, {"name": "黄芩", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}, {"name": "人参", "dosage": "三两"}, {"name": "黄连", "dosage": "一两"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "炙甘草", "dosage": "三两"}],
     "indication": "妇人吐涎沫，医反下之，心下即痞。",
     "contraindication": "无寒热错杂者慎用。", "explanation": "误下成痞。半夏泻心汤辛开苦降。", "keywords": ["吐涎沫", "心下痞", "误下"]},
    {"id": "gancao_xiexin_tang_jj", "name": "甘草泻心汤", "alias": "", "meridian": "少阳/太阴", "category": "辛开苦降剂",
     "components": [{"name": "炙甘草", "dosage": "四两"}, {"name": "黄芩", "dosage": "三两"}, {"name": "干姜", "dosage": "三两"}, {"name": "半夏", "dosage": "半升"}, {"name": "大枣", "dosage": "十二枚"}, {"name": "黄连", "dosage": "一两"}, {"name": "人参", "dosage": "三两"}],
     "indication": "妇人阴中蚀疮烂者。",
     "contraindication": "无寒热错杂者慎用。", "explanation": "狐惑病阴部蚀疮。甘草泻心汤辛开苦降清热。", "keywords": ["阴中蚀疮", "狐惑"]},
    {"id": "langdangwan", "name": "狼牙汤", "alias": "", "meridian": "外用", "category": "清热杀虫剂",
     "components": [{"name": "狼牙", "dosage": "三两", "role": "清热杀虫"}],
     "indication": "妇人阴中生疮。",
     "contraindication": "内服有毒，仅可外用。", "explanation": "外用杀虫止痒。狼牙即牙子（狼牙草）。", "keywords": ["阴中生疮", "外洗"]},
    {"id": "shechuangzi_san", "name": "蛇床子散", "alias": "", "meridian": "外用", "category": "燥湿杀虫剂",
     "components": [{"name": "蛇床子", "dosage": "适量", "role": "燥湿杀虫"}],
     "indication": "妇人阴寒。",
     "contraindication": "内服需慎。", "explanation": "外用燥湿杀虫止痒。蛇床子为外治妇科要药。", "keywords": ["阴寒", "外用"]},
    {"id": "xiong_gui_tang", "name": "温经汤", "alias": "", "meridian": "肝/冲脉", "category": "温经补血剂",
     "components": [{"name": "吴茱萸", "dosage": "三两"}, {"name": "当归", "dosage": "二两"}, {"name": "川芎", "dosage": "二两"}, {"name": "芍药", "dosage": "二两"}, {"name": "人参", "dosage": "二两"}, {"name": "桂枝", "dosage": "二两"}, {"name": "阿胶", "dosage": "二两"}, {"name": "丹皮", "dosage": "二两"}, {"name": "生姜", "dosage": "二两"}, {"name": "甘草", "dosage": "二两"}, {"name": "半夏", "dosage": "半升"}, {"name": "麦冬", "dosage": "一升"}],
     "indication": "妇人少腹寒，久不受胎。兼取崩中去血，或月水来过多，及至期不来。",
     "contraindication": "血热者慎用。", "explanation": "冲任虚寒兼瘀。温经汤温经散寒、养血调经。吴茱萸桂枝温经，归芍芎养血，阿胶麦冬滋阴，丹皮活血。倪师治月经病常用此方。", "keywords": ["少腹寒", "久不受胎", "崩中", "月经不调"]},
    {"id": "zizhisan", "name": "紫参汤", "alias": "", "meridian": "肺/大肠", "category": "清热止利剂",
     "components": [{"name": "紫参", "dosage": "半斤"}, {"name": "甘草", "dosage": "三两"}],
     "indication": "下利肺痛。",
     "contraindication": "虚寒下利者慎用。", "explanation": "紫参清热解毒止利，甘草和中。肺与大肠相表里，下利+肺痛=热利。", "keywords": ["下利", "肺痛"]},
    {"id": "helisan", "name": "诃黎勒散", "alias": "", "meridian": "大肠", "category": "涩肠固脱剂",
     "components": [{"name": "诃黎勒", "dosage": "十枚", "role": "涩肠止利"}],
     "indication": "气利（矢气时大便随之而出）。",
     "contraindication": "湿热初起者忌涩。", "explanation": "气虚下陷，大便随矢气而出。诃黎勒涩肠固脱。散剂顿服。", "keywords": ["气利", "矢气下利", "涩肠"]},
]

# 去重
seen = set()
unique = []
for f in JINGUI_FORMULAS:
    if f['id'] not in seen:
        seen.add(f['id'])
        unique.append(f)

print(f"Generated {len(unique)} unique formulas")

with open('_jingui_formulas.json', 'w', encoding='utf-8') as f:
    json.dump(unique, f, ensure_ascii=False, indent=2)
print("Saved to _jingui_formulas.json")
